apiVersion: v1
kind: Service
metadata:
  name: slack-app
  namespace: integrations
  labels:
    app: slack-app
spec:
  ports:
    - port: 8000
  selector:
    app: slack-app
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: slack-app
  namespace: integrations
  labels:
    app: slack-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slack-app
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: slack-app
    spec:
      containers:
        - name: slack-app
          image: docker.io/{{DOCKERHUB_USERNAME}}/fyle_slack-app:{{RELEASE_VERSION}}
          resources:
            limits:
              memory: 300Mi
            requests:
              memory: 250Mi
          env:
            - name: GET_HOSTS_FROM
              value: dns
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /api/workspaces/ready/
              port: 8000
            initialDelaySeconds: 10
            timeoutSeconds: 1
          envFrom:
            - secretRef:
                name: slack-app-secrets
      imagePullSecrets:
        - name: myregistrykey2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: slack-app-qcluster
  namespace: integrations
  labels:
    app: slack-app-qcluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slack-app-qcluster
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: slack-app-qcluster
    spec:
      containers:
        - name: slack-app
          image: docker.io/{{DOCKERHUB_USERNAME}}/fyle_slack-app:{{RELEASE_VERSION}}
          command: ['/bin/bash', 'start_qcluster.sh']
          resources:
            limits:
              memory: 400Mi
            requests:
              memory: 350Mi
          env:
            - name: GET_HOSTS_FROM
              value: dns
          envFrom:
            - secretRef:
                name: slack-app-secrets
      imagePullSecrets:
        - name: myregistrykey2
