name: Deploy to Staging

on:
  push:
    branches:
      - master
  pull_request:
    types: [labeled]

jobs:
  staging_deploy:
    if: (github.event_name != 'pull_request') || (github.event_name == 'pull_request' && github.event.action == 'labeled' && github.event.label.name == 'deploy')
    runs-on: ubuntu-latest

apiVersion: v1
kind: Service
metadata:
  name: slack-app
  namespace: slack
  labels:
    app: slack-app
spec:
  type: ClusterIP
  ports:
    - port: 8000
  selector:
    app: slack-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: slack-app
  namespace: slack
  labels:
    app: slack-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slack-app
  strategy:
    type: RollingUpdateing
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: slack-app
    spec:
      containers:
        - name: slack-app
          image: docker.io/sivafyle/fyle_slack-app:${version}
          resources:
            limits:
              memory: 200Mi
            requests:
              memory: 200Mi
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
            initialDelaySeconds: 10
            timeoutSeconds: 1
      terminationGracePeriodSeconds: 60
      imagePullSecrets:
        - name: myregistrykey2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: slack-app-qcluster
  namespace: slack
  labels:
    app: slack-app-qcluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slack-app-qcluster
  template:
    metadata:
      labels:
        app: slack-app-qcluster
    spec:
      containers:
        - name: slack-app
          image: docker.io/sivafyle/fyle_slack-app:${version}
          resources:
            limits:
              memory: 400Mi
            requests:
              memory: 400Mi
          command: [ 'bash', 'run_qcluster.sh' ]
      terminationGracePeriodSeconds: 60
      imagePullSecrets:
        - name: myregistrykey2
