# Generated by Django 3.1.6 on 2021-02-11 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FyleEmployee',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('refresh_token', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('org_id', models.CharField(max_length=12)),
                ('org_name', models.CharField(max_length=12)),
                ('org_currency', models.CharField(max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fyle_employees',
            },
        ),
        migrations.CreateModel(
            name='SlackTeam',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('bot_user_id', models.CharField(max_length=120)),
                ('bot_access_token', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'slack_teams',
            },
        ),
        migrations.CreateModel(
            name='SlackUser',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('dm_channel_id', models.CharField(max_length=120, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slack_team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fyle_slack_app.slackteam')),
            ],
            options={
                'db_table': 'slack_users',
            },
        ),
        migrations.CreateModel(
            name='SlackFyleUserMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fyle_employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fyle_slack_app.fyleemployee')),
                ('slack_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fyle_slack_app.slackuser')),
            ],
            options={
                'db_table': 'slack_fyle_user_mappings',
            },
        ),
    ]
