# Generated by Django 3.1.6 on 2021-03-23 10:16

from django.db import connection, migrations

version = '0001'

def run_migration(apps, schema_editor):
    with open('fyle_slack_app/migrations/{}.sql'.format(version)) as fo:
        sql = fo.read()
        with connection.cursor() as c:
            c.execute(sql)


class Migration(migrations.Migration):

    operations = [
        migrations.RunPython(run_migration)
    ]
