# Generated by Django 3.1.6 on 2021-02-17 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('bot_user_id', models.CharField(max_length=120)),
                ('bot_access_token', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'teams',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('slack_user_id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('slack_dm_channel_id', models.CharField(max_length=120, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('fyle_refresh_token', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slack_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fyle_slack_app.team')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
