# Generated by Django 3.1.6 on 2021-03-05 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fyle_slack_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportPollingDetail',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='fyle_slack_app.user')),
                ('last_successful_poll_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'report_polling_details',
            },
        ),
    ]
