# Generated by Django 3.1.6 on 2021-06-10 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fyle_slack_app', '0002_notificationpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscriptionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(max_length=120)),
                ('subscription_id', models.CharField(max_length=120, unique=True)),
                ('webhook_id', models.CharField(max_length=120, unique=True)),
                ('slack_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fyle_slack_app.user', to_field='slack_user_id')),
            ],
            options={
                'db_table': 'user_subscription_details',
                'unique_together': {('slack_user', 'subscription_type')},
            },
        ),
    ]
