# Generated by Django 3.1.6 on 2021-03-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle_slack_app', '0002_reportpollingdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fyle_employee_id',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
