# Generated by Django 3.1.6 on 2021-10-19 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fyle_slack_app', '0003_usersubscriptiondetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseProcessingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_details', models.JSONField(blank=True, null=True)),
                ('slack_view_id', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('form_metadata', models.JSONField(blank=True, null=True)),
                ('is_successfully_processed', models.BooleanField(default=False)),
                ('expense_flow_type', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slack_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fyle_slack_app.user', to_field='slack_user_id')),
            ],
            options={
                'db_table': 'expense_processing_details',
            },
        ),
    ]
