# Generated by Django 3.1.13 on 2022-01-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle_slack_app', '0003_usersubscriptiondetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fyle_org_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
