# Generated by Django 3.1.6 on 2022-01-17 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fyle_slack_app', '0003_usersubscriptiondetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_trigger', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_feedback_shown_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fyle_slack_app.user', to_field='slack_user_id')),
            ],
            options={
                'db_table': 'user_feedbacks',
            },
        ),
        migrations.CreateModel(
            name='UserFeedbackResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_feedback', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fyle_slack_app.userfeedback')),
            ],
            options={
                'db_table': 'user_feedback_responses',
            },
        ),
    ]
