# Generated by Django 3.1.6 on 2021-03-23 10:16

from django.db import connection, migrations


def run_migration(apps, schema_editor):
    with open('fyle_slack_app/migrations/1.sql') as fo:
        sql = fo.read()
        with connection.cursor() as c:
            c.execute(sql)


class Migration(migrations.Migration):

    operations = [
        migrations.RunPython(run_migration)
    ]
