expense_fields = [
  {
    "id": 6182,
    "created_at": "2021-04-22T07:46:07.007Z",
    "created_by": {
      "user_id": "SYSTEM",
      "org_user_id": None,
      "org_id": None,
      "roles": [],
      "scopes": [],
      "allowed_CIDRs": None,
      "cluster_domain": None,
      "proxy_org_user_id": None,
      "tpa_id": None,
      "tpa_name": None,
      "name": None
    },
    "updated_at": "2021-04-22T07:48:35.072Z",
    "updated_by": {
      "user_id": "usuTaTN12iqG",
      "org_user_id": "ouZH5KbJaBFq",
      "org_id": "orsReFb3Oou8",
      "roles": [
        "OWNER",
        "FYLER",
        "ADMIN"
      ],
      "scopes": [],
      "allowed_CIDRs": [],
      "cluster_domain": "\"https://staging.fyle.tech\"",
      "proxy_org_user_id": None,
      "tpa_id": None,
      "tpa_name": None,
      "name": "ouZH5KbJaBFq"
    },
    "org_id": "orsReFb3Oou8",
    "column_name": "bus_travel_class",
    "field_name": "Travel Class",
    "seq": 1,
    "type": "TEXT",
    "is_custom": False,
    "is_enabled": True,
    "is_mandatory": False,
    "placeholder": "Enter class of travel",
    "default_value": None,
    "options": [],
    "org_category_ids": [
      136517
    ],
    "code": None,
    "roles_editable": [
      "FYLER",
      "APPROVER",
      "TRAVEL_ADMIN",
      "VERIFIER",
      "PAYMENT_PROCESSOR",
      "FINANCE",
      "ADMIN",
      "TRAVEL_AGENT",
      "OWNER",
      "AUDITOR"
    ]
  },
  {
    "id": 6183,
    "created_at": "2021-04-22T07:46:07.007Z",
    "created_by": {
      "user_id": "SYSTEM",
      "org_user_id": None,
      "org_id": None,
      "roles": [],
      "scopes": [],
      "allowed_CIDRs": None,
      "cluster_domain": None,
      "proxy_org_user_id": None,
      "tpa_id": None,
      "tpa_name": None,
      "name": None
    },
    "updated_at": "2021-04-22T07:48:35.072Z",
    "updated_by": {
      "user_id": "usuTaTN12iqG",
      "org_user_id": "ouZH5KbJaBFq",
      "org_id": "orsReFb3Oou8",
      "roles": [
        "OWNER",
        "FYLER",
        "ADMIN"
      ],
      "scopes": [],
      "allowed_CIDRs": [],
      "cluster_domain": "\"https://staging.fyle.tech\"",
      "proxy_org_user_id": None,
      "tpa_id": None,
      "tpa_name": None,
      "name": "ouZH5KbJaBFq"
    },
    "org_id": "orsReFb3Oou8",
    "column_name": "cost_center_id",
    "field_name": "Cost Center",
    "seq": 1,
    "type": "SELECT",
    "is_custom": False,
    "is_enabled": True,
    "is_mandatory": False,
    "placeholder": "Select Cost Center",
    "default_value": None,
    "options": [],
    "org_category_ids": [
      136506,
      136507,
      136508,
      136509,
      136510,
      136511,
      136512,
      136513,
      136514,
      136515,
      136516,
      136517,
      136518,
      136519,
      136520,
      136521,
      136522,
      136523,
      136524,
      136525,
      136526,
      136527,
      136528,
      136529,
      136530,
      136531
    ],
    "code": None,
    "roles_editable": [
      "FYLER",
      "APPROVER",
      "TRAVEL_ADMIN",
      "VERIFIER",
      "PAYMENT_PROCESSOR",
      "FINANCE",
      "ADMIN",
      "TRAVEL_AGENT",
      "OWNER",
      "AUDITOR"
    ]
  },
  {
    "id": 6184,
    "created_at": "2021-04-22T07:46:07.007Z",
    "created_by": {
      "user_id": "SYSTEM",
      "org_user_id": None,
      "org_id": None,
      "roles": [],
      "scopes": [],
      "allowed_CIDRs": None,
      "cluster_domain": None,
      "proxy_org_user_id": None,
      "tpa_id": None,
      "tpa_name": None,
      "name": None
    },
    "updated_at": "2021-04-22T07:48:35.072Z",
    "updated_by": {
      "user_id": "usuTaTN12iqG",
      "org_user_id": "ouZH5KbJaBFq",
      "org_id": "orsReFb3Oou8",
      "roles": [
        "OWNER",
        "FYLER",
        "ADMIN"
      ],
      "scopes": [],
      "allowed_CIDRs": [],
      "cluster_domain": "\"https://staging.fyle.tech\"",
      "proxy_org_user_id": None,
      "tpa_id": None,
      "tpa_name": None,
      "name": "ouZH5KbJaBFq"
    },
    "org_id": "orsReFb3Oou8",
    "column_name": "distance",
    "field_name": "Distance",
    "seq": 1,
    "type": "NUMBER",
    "is_custom": False,
    "is_enabled": True,
    "is_mandatory": True,
    "placeholder": "Enter Distance",
    "default_value": None,
    "options": [],
    "org_category_ids": [
      136514
    ],
    "code": None,
    "roles_editable": [
      "FYLER",
      "APPROVER",
      "TRAVEL_ADMIN",
      "VERIFIER",
      "PAYMENT_PROCESSOR",
      "FINANCE",
      "ADMIN",
      "TRAVEL_AGENT",
      "OWNER",
      "AUDITOR"
    ]
  },
  {
    "id": 6185,
    "created_at": "2021-04-22T07:46:07.007Z",
    "created_by": {
      "user_id": "SYSTEM",
      "org_user_id": None,
      "org_id": None,
      "roles": [],
      "scopes": [],
      "allowed_CIDRs": None,
      "cluster_domain": None,
      "proxy_org_user_id": None,
      "tpa_id": None,
      "tpa_name": None,
      "name": None
    },
    "updated_at": "2021-04-22T07:48:35.072Z",
    "updated_by": {
      "user_id": "usuTaTN12iqG",
      "org_user_id": "ouZH5KbJaBFq",
      "org_id": "orsReFb3Oou8",
      "roles": [
        "OWNER",
        "FYLER",
        "ADMIN"
      ],
      "scopes": [],
      "allowed_CIDRs": [],
      "cluster_domain": "\"https://staging.fyle.tech\"",
      "proxy_org_user_id": None,
      "tpa_id": None,
      "tpa_name": None,
      "name": "ouZH5KbJaBFq"
    },
    "org_id": "orsReFb3Oou8",
    "column_name": "distance",
    "field_name": "Distance",
    "seq": 2,
    "type": "NUMBER",
    "is_custom": False,
    "is_enabled": True,
    "is_mandatory": False,
    "placeholder": "Enter Distance",
    "default_value": None,
    "options": [],
    "org_category_ids": [
      136519
    ],
    "code": None,
    "roles_editable": [
      "FYLER",
      "APPROVER",
      "TRAVEL_ADMIN",
      "VERIFIER",
      "PAYMENT_PROCESSOR",
      "FINANCE",
      "ADMIN",
      "TRAVEL_AGENT",
      "OWNER",
      "AUDITOR"
    ]
  },
  {
    "id": 6186,
    "created_at": "2021-04-22T07:46:07.007Z",
    "created_by": {
      "user_id": "SYSTEM",
      "org_user_id": None,
      "org_id": None,
      "roles": [],
      "scopes": [],
      "allowed_CIDRs": None,
      "cluster_domain": None,
      "proxy_org_user_id": None,
      "tpa_id": None,
      "tpa_name": None,
      "name": None
    },
    "updated_at": "2021-04-22T07:48:35.072Z",
    "updated_by": {
      "user_id": "usuTaTN12iqG",
      "org_user_id": "ouZH5KbJaBFq",
      "org_id": "orsReFb3Oou8",
      "roles": [
        "OWNER",
        "FYLER",
        "ADMIN"
      ],
      "scopes": [],
      "allowed_CIDRs": [],
      "cluster_domain": "\"https://staging.fyle.tech\"",
      "proxy_org_user_id": None,
      "tpa_id": None,
      "tpa_name": None,
      "name": "ouZH5KbJaBFq"
    },
    "org_id": "orsReFb3Oou8",
    "column_name": "distance_unit",
    "field_name": "Unit",
    "seq": 1,
    "type": "SELECT",
    "is_custom": False,
    "is_enabled": True,
    "is_mandatory": True,
    "placeholder": "Unit",
    "default_value": "MILES",
    "options": [
      "KM",
      "MILES"
    ],
    "org_category_ids": [
      136514
    ],
    "code": None,
    "roles_editable": [
      "FYLER",
      "APPROVER",
      "TRAVEL_ADMIN",
      "VERIFIER",
      "PAYMENT_PROCESSOR",
      "FINANCE",
      "ADMIN",
      "TRAVEL_AGENT",
      "OWNER",
      "AUDITOR"
    ]
  },
  {
    "id": 6187,
    "created_at": "2021-04-22T07:46:07.007Z",
    "created_by": {
      "user_id": "SYSTEM",
      "org_user_id": None,
      "org_id": None,
      "roles": [],
      "scopes": [],
      "allowed_CIDRs": None,
      "cluster_domain": None,
      "proxy_org_user_id": None,
      "tpa_id": None,
      "tpa_name": None,
      "name": None
    },
    "updated_at": "2021-04-22T07:48:35.072Z",
    "updated_by": {
      "user_id": "usuTaTN12iqG",
      "org_user_id": "ouZH5KbJaBFq",
      "org_id": "orsReFb3Oou8",
      "roles": [
        "OWNER",
        "FYLER",
        "ADMIN"
      ],
      "scopes": [],
      "allowed_CIDRs": [],
      "cluster_domain": "\"https://staging.fyle.tech\"",
      "proxy_org_user_id": None,
      "tpa_id": None,
      "tpa_name": None,
      "name": "ouZH5KbJaBFq"
    },
    "org_id": "orsReFb3Oou8",
    "column_name": "distance_unit",
    "field_name": "Unit",
    "seq": 2,
    "type": "SELECT",
    "is_custom": False,
    "is_enabled": True,
    "is_mandatory": False,
    "placeholder": "Unit",
    "default_value": "MILES",
    "options": [
      "KM",
      "MILES"
    ],
    "org_category_ids": [
      136519
    ],
    "code": None,
    "roles_editable": [
      "FYLER",
      "APPROVER",
      "TRAVEL_ADMIN",
      "VERIFIER",
      "PAYMENT_PROCESSOR",
      "FINANCE",
      "ADMIN",
      "TRAVEL_AGENT",
      "OWNER",
      "AUDITOR"
    ]
  },
  {
    "id": 6188,
    "created_at": "2021-04-22T07:46:07.007Z",
    "created_by": {
      "user_id": "SYSTEM",
      "org_user_id": None,
      "org_id": None,
      "roles": [],
      "scopes": [],
      "allowed_CIDRs": None,
      "cluster_domain": None,
      "proxy_org_user_id": None,
      "tpa_id": None,
      "tpa_name": None,
      "name": None
    },
    "updated_at": "2021-04-22T07:48:35.072Z",
    "updated_by": {
      "user_id": "usuTaTN12iqG",
      "org_user_id": "ouZH5KbJaBFq",
      "org_id": "orsReFb3Oou8",
      "roles": [
        "OWNER",
        "FYLER",
        "ADMIN"
      ],
      "scopes": [],
      "allowed_CIDRs": [],
      "cluster_domain": "\"https://staging.fyle.tech\"",
      "proxy_org_user_id": None,
      "tpa_id": None,
      "tpa_name": None,
      "name": "ouZH5KbJaBFq"
    },
    "org_id": "orsReFb3Oou8",
    "column_name": "flight_journey_travel_class",
    "field_name": "Onward Travel Class",
    "seq": 1,
    "type": "SELECT",
    "is_custom": False,
    "is_enabled": True,
    "is_mandatory": False,
    "placeholder": "Select travel class",
    "default_value": None,
    "options": [
      "BUSINESS",
      "ECONOMY",
      "FIRST_CLASS"
    ],
    "org_category_ids": [
      136525
    ],
    "code": None,
    "roles_editable": [
      "FYLER",
      "APPROVER",
      "TRAVEL_ADMIN",
      "VERIFIER",
      "PAYMENT_PROCESSOR",
      "FINANCE",
      "ADMIN",
      "TRAVEL_AGENT",
      "OWNER",
      "AUDITOR"
    ]
  },
  {
    "id": 6189,
    "created_at": "2021-04-22T07:46:07.007Z",
    "created_by": {
      "user_id": "SYSTEM",
      "org_user_id": None,
      "org_id": None,
      "roles": [],
      "scopes": [],
      "allowed_CIDRs": None,
      "cluster_domain": None,
      "proxy_org_user_id": None,
      "tpa_id": None,
      "tpa_name": None,
      "name": None
    },
    "updated_at": "2021-04-22T07:48:35.072Z",
    "updated_by": {
      "user_id": "usuTaTN12iqG",
      "org_user_id": "ouZH5KbJaBFq",
      "org_id": "orsReFb3Oou8",
      "roles": [
        "OWNER",
        "FYLER",
        "ADMIN"
      ],
      "scopes": [],
      "allowed_CIDRs": [],
      "cluster_domain": "\"https://staging.fyle.tech\"",
      "proxy_org_user_id": None,
      "tpa_id": None,
      "tpa_name": None,
      "name": "ouZH5KbJaBFq"
    },
    "org_id": "orsReFb3Oou8",
    "column_name": "flight_return_travel_class",
    "field_name": "Return Travel Class",
    "seq": 1,
    "type": "SELECT",
    "is_custom": False,
    "is_enabled": True,
    "is_mandatory": False,
    "placeholder": "Select travel class",
    "default_value": None,
    "options": [
      "BUSINESS",
      "ECONOMY",
      "FIRST_CLASS"
    ],
    "org_category_ids": [
      136525
    ],
    "code": None,
    "roles_editable": [
      "FYLER",
      "APPROVER",
      "TRAVEL_ADMIN",
      "VERIFIER",
      "PAYMENT_PROCESSOR",
      "FINANCE",
      "ADMIN",
      "TRAVEL_AGENT",
      "OWNER",
      "AUDITOR"
    ]
  },
  {
    "id": 6190,
    "created_at": "2021-04-22T07:46:07.007Z",
    "created_by": {
      "user_id": "SYSTEM",
      "org_user_id": None,
      "org_id": None,
      "roles": [],
      "scopes": [],
      "allowed_CIDRs": None,
      "cluster_domain": None,
      "proxy_org_user_id": None,
      "tpa_id": None,
      "tpa_name": None,
      "name": None
    },
    "updated_at": "2021-04-22T07:48:35.072Z",
    "updated_by": {
      "user_id": "usuTaTN12iqG",
      "org_user_id": "ouZH5KbJaBFq",
      "org_id": "orsReFb3Oou8",
      "roles": [
        "OWNER",
        "FYLER",
        "ADMIN"
      ],
      "scopes": [],
      "allowed_CIDRs": [],
      "cluster_domain": "\"https://staging.fyle.tech\"",
      "proxy_org_user_id": None,
      "tpa_id": None,
      "tpa_name": None,
      "name": "ouZH5KbJaBFq"
    },
    "org_id": "orsReFb3Oou8",
    "column_name": "from_dt",
    "field_name": "From",
    "seq": 1,
    "type": "DATE",
    "is_custom": False,
    "is_enabled": True,
    "is_mandatory": False,
    "placeholder": "Select Date",
    "default_value": None,
    "options": [],
    "org_category_ids": [
      136516
    ],
    "code": None,
    "roles_editable": [
      "FYLER",
      "APPROVER",
      "TRAVEL_ADMIN",
      "VERIFIER",
      "PAYMENT_PROCESSOR",
      "FINANCE",
      "ADMIN",
      "TRAVEL_AGENT",
      "OWNER",
      "AUDITOR"
    ]
  },
  {
    "id": 6191,
    "created_at": "2021-04-22T07:46:07.007Z",
    "created_by": {
      "user_id": "SYSTEM",
      "org_user_id": None,
      "org_id": None,
      "roles": [],
      "scopes": [],
      "allowed_CIDRs": None,
      "cluster_domain": None,
      "proxy_org_user_id": None,
      "tpa_id": None,
      "tpa_name": None,
      "name": None
    },
    "updated_at": "2021-04-22T07:48:35.072Z",
    "updated_by": {
      "user_id": "usuTaTN12iqG",
      "org_user_id": "ouZH5KbJaBFq",
      "org_id": "orsReFb3Oou8",
      "roles": [
        "OWNER",
        "FYLER",
        "ADMIN"
      ],
      "scopes": [],
      "allowed_CIDRs": [],
      "cluster_domain": "\"https://staging.fyle.tech\"",
      "proxy_org_user_id": None,
      "tpa_id": None,
      "tpa_name": None,
      "name": "ouZH5KbJaBFq"
    },
    "org_id": "orsReFb3Oou8",
    "column_name": "from_dt",
    "field_name": "Onward Date",
    "seq": 2,
    "type": "DATE",
    "is_custom": False,
    "is_enabled": True,
    "is_mandatory": False,
    "placeholder": "Select Date",
    "default_value": None,
    "options": [],
    "org_category_ids": [
      136507,
      136517,
      136525
    ],
    "code": None,
    "roles_editable": [
      "FYLER",
      "APPROVER",
      "TRAVEL_ADMIN",
      "VERIFIER",
      "PAYMENT_PROCESSOR",
      "FINANCE",
      "ADMIN",
      "TRAVEL_AGENT",
      "OWNER",
      "AUDITOR"
    ]
  },
  {
    "id": 6192,
    "created_at": "2021-04-22T07:46:07.007Z",
    "created_by": {
      "user_id": "SYSTEM",
      "org_user_id": None,
      "org_id": None,
      "roles": [],
      "scopes": [],
      "allowed_CIDRs": None,
      "cluster_domain": None,
      "proxy_org_user_id": None,
      "tpa_id": None,
      "tpa_name": None,
      "name": None
    },
    "updated_at": "2021-04-22T07:48:35.072Z",
    "updated_by": {
      "user_id": "usuTaTN12iqG",
      "org_user_id": "ouZH5KbJaBFq",
      "org_id": "orsReFb3Oou8",
      "roles": [
        "OWNER",
        "FYLER",
        "ADMIN"
      ],
      "scopes": [],
      "allowed_CIDRs": [],
      "cluster_domain": "\"https://staging.fyle.tech\"",
      "proxy_org_user_id": None,
      "tpa_id": None,
      "tpa_name": None,
      "name": "ouZH5KbJaBFq"
    },
    "org_id": "orsReFb3Oou8",
    "column_name": "from_dt",
    "field_name": "Check-in Date",
    "seq": 3,
    "type": "DATE",
    "is_custom": False,
    "is_enabled": True,
    "is_mandatory": False,
    "placeholder": "Select Date",
    "default_value": None,
    "options": [],
    "org_category_ids": [
      136521
    ],
    "code": None,
    "roles_editable": [
      "FYLER",
      "APPROVER",
      "TRAVEL_ADMIN",
      "VERIFIER",
      "PAYMENT_PROCESSOR",
      "FINANCE",
      "ADMIN",
      "TRAVEL_AGENT",
      "OWNER",
      "AUDITOR"
    ]
  },
  {
    "id": 6193,
    "created_at": "2021-04-22T07:46:07.007Z",
    "created_by": {
      "user_id": "SYSTEM",
      "org_user_id": None,
      "org_id": None,
      "roles": [],
      "scopes": [],
      "allowed_CIDRs": None,
      "cluster_domain": None,
      "proxy_org_user_id": None,
      "tpa_id": None,
      "tpa_name": None,
      "name": None
    },
    "updated_at": "2021-04-22T07:48:35.072Z",
    "updated_by": {
      "user_id": "usuTaTN12iqG",
      "org_user_id": "ouZH5KbJaBFq",
      "org_id": "orsReFb3Oou8",
      "roles": [
        "OWNER",
        "FYLER",
        "ADMIN"
      ],
      "scopes": [],
      "allowed_CIDRs": [],
      "cluster_domain": "\"https://staging.fyle.tech\"",
      "proxy_org_user_id": None,
      "tpa_id": None,
      "tpa_name": None,
      "name": "ouZH5KbJaBFq"
    },
    "org_id": "orsReFb3Oou8",
    "column_name": "location1",
    "field_name": "From",
    "seq": 1,
    "type": "LOCATION",
    "is_custom": False,
    "is_enabled": True,
    "is_mandatory": False,
    "placeholder": "Select a City",
    "default_value": None,
    "options": [],
    "org_category_ids": [
      136507,
      136517,
      136525
    ],
    "code": None,
    "roles_editable": [
      "FYLER",
      "APPROVER",
      "TRAVEL_ADMIN",
      "VERIFIER",
      "PAYMENT_PROCESSOR",
      "FINANCE",
      "ADMIN",
      "TRAVEL_AGENT",
      "OWNER",
      "AUDITOR"
    ]
  },
  {
    "id": 6194,
    "created_at": "2021-04-22T07:46:07.007Z",
    "created_by": {
      "user_id": "SYSTEM",
      "org_user_id": None,
      "org_id": None,
      "roles": [],
      "scopes": [],
      "allowed_CIDRs": None,
      "cluster_domain": None,
      "proxy_org_user_id": None,
      "tpa_id": None,
      "tpa_name": None,
      "name": None
    },
    "updated_at": "2021-04-22T07:48:35.072Z",
    "updated_by": {
      "user_id": "usuTaTN12iqG",
      "org_user_id": "ouZH5KbJaBFq",
      "org_id": "orsReFb3Oou8",
      "roles": [
        "OWNER",
        "FYLER",
        "ADMIN"
      ],
      "scopes": [],
      "allowed_CIDRs": [],
      "cluster_domain": "\"https://staging.fyle.tech\"",
      "proxy_org_user_id": None,
      "tpa_id": None,
      "tpa_name": None,
      "name": "ouZH5KbJaBFq"
    },
    "org_id": "orsReFb3Oou8",
    "column_name": "location1",
    "field_name": "City",
    "seq": 2,
    "type": "LOCATION",
    "is_custom": False,
    "is_enabled": True,
    "is_mandatory": False,
    "placeholder": "Select a City",
    "default_value": None,
    "options": [],
    "org_category_ids": [
      136521
    ],
    "code": None,
    "roles_editable": [
      "FYLER",
      "APPROVER",
      "TRAVEL_ADMIN",
      "VERIFIER",
      "PAYMENT_PROCESSOR",
      "FINANCE",
      "ADMIN",
      "TRAVEL_AGENT",
      "OWNER",
      "AUDITOR"
    ]
  },
  {
    "id": 6195,
    "created_at": "2021-04-22T07:46:07.007Z",
    "created_by": {
      "user_id": "SYSTEM",
      "org_user_id": None,
      "org_id": None,
      "roles": [],
      "scopes": [],
      "allowed_CIDRs": None,
      "cluster_domain": None,
      "proxy_org_user_id": None,
      "tpa_id": None,
      "tpa_name": None,
      "name": None
    },
    "updated_at": "2021-04-22T07:48:35.072Z",
    "updated_by": {
      "user_id": "usuTaTN12iqG",
      "org_user_id": "ouZH5KbJaBFq",
      "org_id": "orsReFb3Oou8",
      "roles": [
        "OWNER",
        "FYLER",
        "ADMIN"
      ],
      "scopes": [],
      "allowed_CIDRs": [],
      "cluster_domain": "\"https://staging.fyle.tech\"",
      "proxy_org_user_id": None,
      "tpa_id": None,
      "tpa_name": None,
      "name": "ouZH5KbJaBFq"
    },
    "org_id": "orsReFb3Oou8",
    "column_name": "location1",
    "field_name": "From",
    "seq": 3,
    "type": "LOCATION",
    "is_custom": False,
    "is_enabled": True,
    "is_mandatory": False,
    "placeholder": "Choose Location - Search for Place or Area",
    "default_value": None,
    "options": [],
    "org_category_ids": [
      136514
    ],
    "code": None,
    "roles_editable": [
      "FYLER",
      "APPROVER",
      "TRAVEL_ADMIN",
      "VERIFIER",
      "PAYMENT_PROCESSOR",
      "FINANCE",
      "ADMIN",
      "TRAVEL_AGENT",
      "OWNER",
      "AUDITOR"
    ]
  },
  {
    "id": 6196,
    "created_at": "2021-04-22T07:46:07.007Z",
    "created_by": {
      "user_id": "SYSTEM",
      "org_user_id": None,
      "org_id": None,
      "roles": [],
      "scopes": [],
      "allowed_CIDRs": None,
      "cluster_domain": None,
      "proxy_org_user_id": None,
      "tpa_id": None,
      "tpa_name": None,
      "name": None
    },
    "updated_at": "2021-04-22T07:48:35.072Z",
    "updated_by": {
      "user_id": "usuTaTN12iqG",
      "org_user_id": "ouZH5KbJaBFq",
      "org_id": "orsReFb3Oou8",
      "roles": [
        "OWNER",
        "FYLER",
        "ADMIN"
      ],
      "scopes": [],
      "allowed_CIDRs": [],
      "cluster_domain": "\"https://staging.fyle.tech\"",
      "proxy_org_user_id": None,
      "tpa_id": None,
      "tpa_name": None,
      "name": "ouZH5KbJaBFq"
    },
    "org_id": "orsReFb3Oou8",
    "column_name": "location2",
    "field_name": "To",
    "seq": 1,
    "type": "LOCATION",
    "is_custom": False,
    "is_enabled": True,
    "is_mandatory": False,
    "placeholder": "Select a City",
    "default_value": None,
    "options": [],
    "org_category_ids": [
      136507,
      136517,
      136525
    ],
    "code": None,
    "roles_editable": [
      "FYLER",
      "APPROVER",
      "TRAVEL_ADMIN",
      "VERIFIER",
      "PAYMENT_PROCESSOR",
      "FINANCE",
      "ADMIN",
      "TRAVEL_AGENT",
      "OWNER",
      "AUDITOR"
    ]
  },
  {
    "id": 6197,
    "created_at": "2021-04-22T07:46:07.007Z",
    "created_by": {
      "user_id": "SYSTEM",
      "org_user_id": None,
      "org_id": None,
      "roles": [],
      "scopes": [],
      "allowed_CIDRs": None,
      "cluster_domain": None,
      "proxy_org_user_id": None,
      "tpa_id": None,
      "tpa_name": None,
      "name": None
    },
    "updated_at": "2021-04-22T07:48:35.072Z",
    "updated_by": {
      "user_id": "usuTaTN12iqG",
      "org_user_id": "ouZH5KbJaBFq",
      "org_id": "orsReFb3Oou8",
      "roles": [
        "OWNER",
        "FYLER",
        "ADMIN"
      ],
      "scopes": [],
      "allowed_CIDRs": [],
      "cluster_domain": "\"https://staging.fyle.tech\"",
      "proxy_org_user_id": None,
      "tpa_id": None,
      "tpa_name": None,
      "name": "ouZH5KbJaBFq"
    },
    "org_id": "orsReFb3Oou8",
    "column_name": "location2",
    "field_name": "To",
    "seq": 2,
    "type": "LOCATION",
    "is_custom": False,
    "is_enabled": True,
    "is_mandatory": False,
    "placeholder": "Choose Location - Search for Place or Area",
    "default_value": None,
    "options": [],
    "org_category_ids": [
      136514
    ],
    "code": None,
    "roles_editable": [
      "FYLER",
      "APPROVER",
      "TRAVEL_ADMIN",
      "VERIFIER",
      "PAYMENT_PROCESSOR",
      "FINANCE",
      "ADMIN",
      "TRAVEL_AGENT",
      "OWNER",
      "AUDITOR"
    ]
  },
  {
    "id": 6198,
    "created_at": "2021-04-22T07:46:07.007Z",
    "created_by": {
      "user_id": "SYSTEM",
      "org_user_id": None,
      "org_id": None,
      "roles": [],
      "scopes": [],
      "allowed_CIDRs": None,
      "cluster_domain": None,
      "proxy_org_user_id": None,
      "tpa_id": None,
      "tpa_name": None,
      "name": None
    },
    "updated_at": "2021-04-22T07:48:35.072Z",
    "updated_by": {
      "user_id": "usuTaTN12iqG",
      "org_user_id": "ouZH5KbJaBFq",
      "org_id": "orsReFb3Oou8",
      "roles": [
        "OWNER",
        "FYLER",
        "ADMIN"
      ],
      "scopes": [],
      "allowed_CIDRs": [],
      "cluster_domain": "\"https://staging.fyle.tech\"",
      "proxy_org_user_id": None,
      "tpa_id": None,
      "tpa_name": None,
      "name": "ouZH5KbJaBFq"
    },
    "org_id": "orsReFb3Oou8",
    "column_name": "num_days",
    "field_name": "No. of Days",
    "seq": 1,
    "type": "NUMBER",
    "is_custom": False,
    "is_enabled": True,
    "is_mandatory": False,
    "placeholder": "No. of Days",
    "default_value": None,
    "options": [],
    "org_category_ids": [
      136516
    ],
    "code": None,
    "roles_editable": [
      "FYLER",
      "APPROVER",
      "TRAVEL_ADMIN",
      "VERIFIER",
      "PAYMENT_PROCESSOR",
      "FINANCE",
      "ADMIN",
      "TRAVEL_AGENT",
      "OWNER",
      "AUDITOR"
    ]
  },
  {
    "id": 6199,
    "created_at": "2021-04-22T07:46:07.007Z",
    "created_by": {
      "user_id": "SYSTEM",
      "org_user_id": None,
      "org_id": None,
      "roles": [],
      "scopes": [],
      "allowed_CIDRs": None,
      "cluster_domain": None,
      "proxy_org_user_id": None,
      "tpa_id": None,
      "tpa_name": None,
      "name": None
    },
    "updated_at": "2021-04-22T07:48:35.072Z",
    "updated_by": {
      "user_id": "usuTaTN12iqG",
      "org_user_id": "ouZH5KbJaBFq",
      "org_id": "orsReFb3Oou8",
      "roles": [
        "OWNER",
        "FYLER",
        "ADMIN"
      ],
      "scopes": [],
      "allowed_CIDRs": [],
      "cluster_domain": "\"https://staging.fyle.tech\"",
      "proxy_org_user_id": None,
      "tpa_id": None,
      "tpa_name": None,
      "name": "ouZH5KbJaBFq"
    },
    "org_id": "orsReFb3Oou8",
    "column_name": "purpose",
    "field_name": "Purpose",
    "seq": 1,
    "type": "TEXT",
    "is_custom": False,
    "is_enabled": True,
    "is_mandatory": False,
    "placeholder": "E.g. Client Meeting",
    "default_value": None,
    "options": [],
    "org_category_ids": [
      136506,
      136507,
      136508,
      136509,
      136510,
      136511,
      136512,
      136513,
      136514,
      136515,
      136516,
      136517,
      136518,
      136519,
      136520,
      136521,
      136522,
      136523,
      136524,
      136525,
      136526,
      136527,
      136528,
      136529,
      136530,
      136531
    ],
    "code": None,
    "roles_editable": [
      "FYLER",
      "APPROVER",
      "TRAVEL_ADMIN",
      "VERIFIER",
      "PAYMENT_PROCESSOR",
      "FINANCE",
      "ADMIN",
      "TRAVEL_AGENT",
      "OWNER",
      "AUDITOR"
    ]
  },
  {
    "id": 6200,
    "created_at": "2021-04-22T07:46:07.007Z",
    "created_by": {
      "user_id": "SYSTEM",
      "org_user_id": None,
      "org_id": None,
      "roles": [],
      "scopes": [],
      "allowed_CIDRs": None,
      "cluster_domain": None,
      "proxy_org_user_id": None,
      "tpa_id": None,
      "tpa_name": None,
      "name": None
    },
    "updated_at": "2021-04-22T07:48:35.072Z",
    "updated_by": {
      "user_id": "usuTaTN12iqG",
      "org_user_id": "ouZH5KbJaBFq",
      "org_id": "orsReFb3Oou8",
      "roles": [
        "OWNER",
        "FYLER",
        "ADMIN"
      ],
      "scopes": [],
      "allowed_CIDRs": [],
      "cluster_domain": "\"https://staging.fyle.tech\"",
      "proxy_org_user_id": None,
      "tpa_id": None,
      "tpa_name": None,
      "name": "ouZH5KbJaBFq"
    },
    "org_id": "orsReFb3Oou8",
    "column_name": "to_dt",
    "field_name": "To",
    "seq": 1,
    "type": "DATE",
    "is_custom": False,
    "is_enabled": True,
    "is_mandatory": False,
    "placeholder": "Select Date",
    "default_value": None,
    "options": [],
    "org_category_ids": [
      136516
    ],
    "code": None,
    "roles_editable": [
      "FYLER",
      "APPROVER",
      "TRAVEL_ADMIN",
      "VERIFIER",
      "PAYMENT_PROCESSOR",
      "FINANCE",
      "ADMIN",
      "TRAVEL_AGENT",
      "OWNER",
      "AUDITOR"
    ]
  },
  {
    "id": 6201,
    "created_at": "2021-04-22T07:46:07.007Z",
    "created_by": {
      "user_id": "SYSTEM",
      "org_user_id": None,
      "org_id": None,
      "roles": [],
      "scopes": [],
      "allowed_CIDRs": None,
      "cluster_domain": None,
      "proxy_org_user_id": None,
      "tpa_id": None,
      "tpa_name": None,
      "name": None
    },
    "updated_at": "2021-04-22T07:48:35.072Z",
    "updated_by": {
      "user_id": "usuTaTN12iqG",
      "org_user_id": "ouZH5KbJaBFq",
      "org_id": "orsReFb3Oou8",
      "roles": [
        "OWNER",
        "FYLER",
        "ADMIN"
      ],
      "scopes": [],
      "allowed_CIDRs": [],
      "cluster_domain": "\"https://staging.fyle.tech\"",
      "proxy_org_user_id": None,
      "tpa_id": None,
      "tpa_name": None,
      "name": "ouZH5KbJaBFq"
    },
    "org_id": "orsReFb3Oou8",
    "column_name": "to_dt",
    "field_name": "Return Date",
    "seq": 2,
    "type": "DATE",
    "is_custom": False,
    "is_enabled": True,
    "is_mandatory": False,
    "placeholder": "Select Date",
    "default_value": None,
    "options": [],
    "org_category_ids": [
      136507,
      136517,
      136525
    ],
    "code": None,
    "roles_editable": [
      "FYLER",
      "APPROVER",
      "TRAVEL_ADMIN",
      "VERIFIER",
      "PAYMENT_PROCESSOR",
      "FINANCE",
      "ADMIN",
      "TRAVEL_AGENT",
      "OWNER",
      "AUDITOR"
    ]
  },
  {
    "id": 6202,
    "created_at": "2021-04-22T07:46:07.007Z",
    "created_by": {
      "user_id": "SYSTEM",
      "org_user_id": None,
      "org_id": None,
      "roles": [],
      "scopes": [],
      "allowed_CIDRs": None,
      "cluster_domain": None,
      "proxy_org_user_id": None,
      "tpa_id": None,
      "tpa_name": None,
      "name": None
    },
    "updated_at": "2021-04-22T07:48:35.072Z",
    "updated_by": {
      "user_id": "usuTaTN12iqG",
      "org_user_id": "ouZH5KbJaBFq",
      "org_id": "orsReFb3Oou8",
      "roles": [
        "OWNER",
        "FYLER",
        "ADMIN"
      ],
      "scopes": [],
      "allowed_CIDRs": [],
      "cluster_domain": "\"https://staging.fyle.tech\"",
      "proxy_org_user_id": None,
      "tpa_id": None,
      "tpa_name": None,
      "name": "ouZH5KbJaBFq"
    },
    "org_id": "orsReFb3Oou8",
    "column_name": "to_dt",
    "field_name": "Check-out Date",
    "seq": 3,
    "type": "DATE",
    "is_custom": False,
    "is_enabled": True,
    "is_mandatory": False,
    "placeholder": "Select Date",
    "default_value": None,
    "options": [],
    "org_category_ids": [
      136521
    ],
    "code": None,
    "roles_editable": [
      "FYLER",
      "APPROVER",
      "TRAVEL_ADMIN",
      "VERIFIER",
      "PAYMENT_PROCESSOR",
      "FINANCE",
      "ADMIN",
      "TRAVEL_AGENT",
      "OWNER",
      "AUDITOR"
    ]
  },
  {
    "id": 6199,
    "created_at": "2021-04-22T07:46:07.007Z",
    "created_by": {
      "user_id": "SYSTEM",
      "org_user_id": None,
      "org_id": None,
      "roles": [],
      "scopes": [],
      "allowed_CIDRs": None,
      "cluster_domain": None,
      "proxy_org_user_id": None,
      "tpa_id": None,
      "tpa_name": None,
      "name": None
    },
    "updated_at": "2021-04-22T07:48:35.072Z",
    "updated_by": {
      "user_id": "usuTaTN12iqG",
      "org_user_id": "ouZH5KbJaBFq",
      "org_id": "orsReFb3Oou8",
      "roles": [
        "OWNER",
        "FYLER",
        "ADMIN"
      ],
      "scopes": [],
      "allowed_CIDRs": [],
      "cluster_domain": "\"https://staging.fyle.tech\"",
      "proxy_org_user_id": None,
      "tpa_id": None,
      "tpa_name": None,
      "name": "ouZH5KbJaBFq"
    },
    "org_id": "orsReFb3Oou8",
    "column_name": "train_travel_class",
    "field_name": "Travel class",
    "seq": 1,
    "type": "TEXT",
    "is_custom": False,
    "is_enabled": True,
    "is_mandatory": False,
    "placeholder": "Enter class of travel",
    "default_value": None,
    "options": [],
    "org_category_ids": [
      136507
    ],
    "code": None,
    "roles_editable": [
      "FYLER",
      "APPROVER",
      "TRAVEL_ADMIN",
      "VERIFIER",
      "PAYMENT_PROCESSOR",
      "FINANCE",
      "ADMIN",
      "TRAVEL_AGENT",
      "OWNER",
      "AUDITOR"
    ]
  },
  {
    "id": 6204,
    "created_at": "2021-04-22T07:46:07.007Z",
    "created_by": {
      "user_id": "SYSTEM",
      "org_user_id": None,
      "org_id": None,
      "roles": [],
      "scopes": [],
      "allowed_CIDRs": None,
      "cluster_domain": None,
      "proxy_org_user_id": None,
      "tpa_id": None,
      "tpa_name": None,
      "name": None
    },
    "updated_at": "2021-04-22T07:48:35.072Z",
    "updated_by": {
      "user_id": "usuTaTN12iqG",
      "org_user_id": "ouZH5KbJaBFq",
      "org_id": "orsReFb3Oou8",
      "roles": [
        "OWNER",
        "FYLER",
        "ADMIN"
      ],
      "scopes": [],
      "allowed_CIDRs": [],
      "cluster_domain": "\"https://staging.fyle.tech\"",
      "proxy_org_user_id": None,
      "tpa_id": None,
      "tpa_name": None,
      "name": "ouZH5KbJaBFq"
    },
    "org_id": "orsReFb3Oou8",
    "column_name": "txn_dt",
    "field_name": "Date of Spend",
    "seq": 1,
    "type": "DATE",
    "is_custom": False,
    "is_enabled": True,
    "is_mandatory": True,
    "placeholder": "Select Date",
    "default_value": None,
    "options": [],
    "org_category_ids": [
      136506,
      136507,
      136508,
      136509,
      136510,
      136511,
      136512,
      136513,
      136515,
      136516,
      136517,
      136518,
      136519,
      136520,
      136521,
      136522,
      136523,
      136524,
      136525,
      136526,
      136527,
      136528,
      136529,
      136530,
      136531
    ],
    "code": None,
    "roles_editable": [
      "FYLER",
      "APPROVER",
      "TRAVEL_ADMIN",
      "VERIFIER",
      "PAYMENT_PROCESSOR",
      "FINANCE",
      "ADMIN",
      "TRAVEL_AGENT",
      "OWNER",
      "AUDITOR"
    ]
  },
  {
    "id": 6205,
    "created_at": "2021-04-22T07:46:07.007Z",
    "created_by": {
      "user_id": "SYSTEM",
      "org_user_id": None,
      "org_id": None,
      "roles": [],
      "scopes": [],
      "allowed_CIDRs": None,
      "cluster_domain": None,
      "proxy_org_user_id": None,
      "tpa_id": None,
      "tpa_name": None,
      "name": None
    },
    "updated_at": "2021-04-22T07:48:35.072Z",
    "updated_by": {
      "user_id": "usuTaTN12iqG",
      "org_user_id": "ouZH5KbJaBFq",
      "org_id": "orsReFb3Oou8",
      "roles": [
        "OWNER",
        "FYLER",
        "ADMIN"
      ],
      "scopes": [],
      "allowed_CIDRs": [],
      "cluster_domain": "\"https://staging.fyle.tech\"",
      "proxy_org_user_id": None,
      "tpa_id": None,
      "tpa_name": None,
      "name": "ouZH5KbJaBFq"
    },
    "org_id": "orsReFb3Oou8",
    "column_name": "txn_dt",
    "field_name": "Date of Travel",
    "seq": 2,
    "type": "DATE",
    "is_custom": False,
    "is_enabled": True,
    "is_mandatory": True,
    "placeholder": "Select Date",
    "default_value": None,
    "options": [],
    "org_category_ids": [
      136514
    ],
    "code": None,
    "roles_editable": [
      "FYLER",
      "APPROVER",
      "TRAVEL_ADMIN",
      "VERIFIER",
      "PAYMENT_PROCESSOR",
      "FINANCE",
      "ADMIN",
      "TRAVEL_AGENT",
      "OWNER",
      "AUDITOR"
    ]
  },
  {
    "id": 6206,
    "created_at": "2021-04-22T07:46:07.007Z",
    "created_by": {
      "user_id": "SYSTEM",
      "org_user_id": None,
      "org_id": None,
      "roles": [],
      "scopes": [],
      "allowed_CIDRs": None,
      "cluster_domain": None,
      "proxy_org_user_id": None,
      "tpa_id": None,
      "tpa_name": None,
      "name": None
    },
    "updated_at": "2021-04-22T07:48:35.072Z",
    "updated_by": {
      "user_id": "usuTaTN12iqG",
      "org_user_id": "ouZH5KbJaBFq",
      "org_id": "orsReFb3Oou8",
      "roles": [
        "OWNER",
        "FYLER",
        "ADMIN"
      ],
      "scopes": [],
      "allowed_CIDRs": [],
      "cluster_domain": "\"https://staging.fyle.tech\"",
      "proxy_org_user_id": None,
      "tpa_id": None,
      "tpa_name": None,
      "name": "ouZH5KbJaBFq"
    },
    "org_id": "orsReFb3Oou8",
    "column_name": "vendor_id",
    "field_name": "Merchant",
    "seq": 1,
    "type": "SELECT",
    "is_custom": False,
    "is_enabled": True,
    "is_mandatory": False,
    "placeholder": "E.g. Uber",
    "default_value": None,
    "options": [],
    "org_category_ids": [
      136507,
      136508,
      136509,
      136510,
      136511,
      136512,
      136513,
      136515,
      136517,
      136518,
      136519,
      136520,
      136521,
      136522,
      136523,
      136524,
      136525,
      136526,
      136527,
      136528,
      136529,
      136530,
      136531
    ],
    "code": None,
    "roles_editable": [
      "FYLER",
      "APPROVER",
      "TRAVEL_ADMIN",
      "VERIFIER",
      "PAYMENT_PROCESSOR",
      "FINANCE",
      "ADMIN",
      "TRAVEL_AGENT",
      "OWNER",
      "AUDITOR"
    ]
  },
  {
    "id": 185323,
    "created_at": "2021-07-28T08:48:55.152Z",
    "created_by": {
      "user_id": "SYSTEM",
      "org_user_id": None,
      "org_id": None,
      "roles": [],
      "scopes": [],
      "allowed_CIDRs": None,
      "cluster_domain": None,
      "proxy_org_user_id": None,
      "tpa_id": None,
      "tpa_name": None,
      "name": None
    },
    "updated_at": "2021-07-28T08:48:55.152Z",
    "updated_by": {
      "user_id": "SYSTEM",
      "org_user_id": None,
      "org_id": None,
      "roles": [],
      "scopes": [],
      "allowed_CIDRs": None,
      "cluster_domain": None,
      "proxy_org_user_id": None,
      "tpa_id": None,
      "tpa_name": None,
      "name": None
    },
    "org_id": "orsReFb3Oou8",
    "column_name": "project_id",
    "field_name": "Project",
    "seq": 1,
    "type": "SELECT",
    "is_custom": False,
    "is_enabled": True,
    "is_mandatory": False,
    "placeholder": "Select Project",
    "default_value": None,
    "options": [],
    "org_category_ids": [],
    "code": None,
    "roles_editable": [
      "FYLER",
      "APPROVER",
      "TRAVEL_ADMIN",
      "VERIFIER",
      "PAYMENT_PROCESSOR",
      "FINANCE",
      "ADMIN",
      "TRAVEL_AGENT",
      "OWNER",
      "AUDITOR"
    ]
  },
  {
    "id": 189621,
    "created_at": "2021-07-29T11:05:38.811Z",
    "created_by": {
      "user_id": "SYSTEM",
      "org_user_id": None,
      "org_id": None,
      "roles": [],
      "scopes": [],
      "allowed_CIDRs": None,
      "cluster_domain": None,
      "proxy_org_user_id": None,
      "tpa_id": None,
      "tpa_name": None,
      "name": None
    },
    "updated_at": "2021-07-29T11:05:38.811Z",
    "updated_by": {
      "user_id": "SYSTEM",
      "org_user_id": None,
      "org_id": None,
      "roles": [],
      "scopes": [],
      "allowed_CIDRs": None,
      "cluster_domain": None,
      "proxy_org_user_id": None,
      "tpa_id": None,
      "tpa_name": None,
      "name": None
    },
    "org_id": "orsReFb3Oou8",
    "column_name": "billable",
    "field_name": "Billable",
    "seq": 1,
    "type": "BOOLEAN",
    "is_custom": False,
    "is_enabled": True,
    "is_mandatory": False,
    "placeholder": "Billable",
    "default_value": "False",
    "options": [],
    "org_category_ids": [],
    "code": None,
    "roles_editable": [
      "FYLER",
      "APPROVER",
      "TRAVEL_ADMIN",
      "VERIFIER",
      "PAYMENT_PROCESSOR",
      "FINANCE",
      "ADMIN",
      "TRAVEL_AGENT",
      "OWNER",
      "AUDITOR"
    ]
  },
  {
    "id": 194141,
    "created_at": "2021-08-17T04:48:57.792Z",
    "created_by": {
      "user_id": "SYSTEM",
      "org_user_id": None,
      "org_id": None,
      "roles": [],
      "scopes": [],
      "allowed_CIDRs": None,
      "cluster_domain": None,
      "proxy_org_user_id": None,
      "tpa_id": None,
      "tpa_name": None,
      "name": None
    },
    "updated_at": "2021-08-17T04:48:57.792Z",
    "updated_by": {
      "user_id": "SYSTEM",
      "org_user_id": None,
      "org_id": None,
      "roles": [],
      "scopes": [],
      "allowed_CIDRs": None,
      "cluster_domain": None,
      "proxy_org_user_id": None,
      "tpa_id": None,
      "tpa_name": None,
      "name": None
    },
    "org_id": "orsReFb3Oou8",
    "column_name": "tax_group",
    "field_name": "Tax Group",
    "seq": 1,
    "type": "SELECT",
    "is_custom": False,
    "is_enabled": True,
    "is_mandatory": False,
    "placeholder": "Tax Group",
    "default_value": None,
    "options": [],
    "org_category_ids": [],
    "code": None,
    "roles_editable": [
      "FYLER",
      "APPROVER",
      "TRAVEL_ADMIN",
      "VERIFIER",
      "PAYMENT_PROCESSOR",
      "FINANCE",
      "ADMIN",
      "TRAVEL_AGENT",
      "OWNER",
      "AUDITOR"
    ]
  },
  {
    "id": 195217,
    "created_at": "2021-08-18T07:35:59.906Z",
    "created_by": {
      "user_id": "usuTaTN12iqG",
      "org_user_id": "ouZH5KbJaBFq",
      "org_id": "orsReFb3Oou8",
      "roles": [
        "OWNER",
        "FYLER",
        "ADMIN",
        "APPROVER"
      ],
      "scopes": [],
      "allowed_CIDRs": [],
      "cluster_domain": "\"https://staging.fyle.tech\"",
      "proxy_org_user_id": None,
      "tpa_id": None,
      "tpa_name": None,
      "name": "ouZH5KbJaBFq"
    },
    "updated_at": "2021-08-18T07:35:59.906Z",
    "updated_by": {
      "user_id": "usuTaTN12iqG",
      "org_user_id": "ouZH5KbJaBFq",
      "org_id": "orsReFb3Oou8",
      "roles": [
        "OWNER",
        "FYLER",
        "ADMIN",
        "APPROVER"
      ],
      "scopes": [],
      "allowed_CIDRs": [],
      "cluster_domain": "\"https://staging.fyle.tech\"",
      "proxy_org_user_id": None,
      "tpa_id": None,
      "tpa_name": None,
      "name": "ouZH5KbJaBFq"
    },
    "org_id": "orsReFb3Oou8",
    "column_name": "text_column1",
    "field_name": "TEST 1",
    "seq": 1,
    "type": "TEXT",
    "is_custom": True,
    "is_enabled": True,
    "is_mandatory": True,
    "placeholder": "testiing",
    "default_value": None,
    "options": [],
    "org_category_ids": [
      136520
    ],
    "code": None,
    "roles_editable": [
      "FYLER",
      "APPROVER",
      "TRAVEL_ADMIN",
      "VERIFIER",
      "PAYMENT_PROCESSOR",
      "FINANCE",
      "ADMIN",
      "TRAVEL_AGENT",
      "OWNER",
      "AUDITOR"
    ]
  }
]