expense_fields = [
    {
        "id": 39,
        "org_id": "orrjqbDbeP9p",
        "column_name": "boolean_column7",
        "field_name": "Test BOOLEAN",
        "seq": 1,
        "type": "BOOLEAN",
        "is_custom": True,
        "is_enabled": True,
        "is_mandatory": False,
        "placeholder": "rfve",
        "default_value": None,
        "options": [],
        "org_category_ids": [136518],
        "code": None,
        "roles_editable": [
            "FYLER",
            "APPROVER",
            "TRAVEL_ADMIN",
            "VERIFIER",
            "PAYMENT_PROCESSOR",
            "FINANCE",
            "ADMIN",
            "TRAVEL_AGENT",
            "OWNER",
            "AUDITOR",
        ],
    },
    {
        "id": 83,
        "created_at": "2017-04-06T04:52:07.825Z",
        "org_id": "orrjqbDbeP9p",
        "column_name": "text_array_column3",
        "field_name": "Multi Type",
        "seq": 1,
        "type": "MULTI_SELECT",
        "is_custom": True,
        "is_enabled": True,
        "is_mandatory": False,
        "placeholder": "Multi Type",
        "default_value": None,
        "options": ["Multi 1", "Multi 2", "Multi 3"],
        "org_category_ids": [136250],
        "code": None,
        "roles_editable": [
            "FYLER",
            "APPROVER",
            "TRAVEL_ADMIN",
            "VERIFIER",
            "PAYMENT_PROCESSOR",
            "FINANCE",
            "ADMIN",
            "TRAVEL_AGENT",
            "OWNER",
            "AUDITOR",
        ],
    },
    {
        "id": 6182,
        "created_at": "2021-04-22T07:46:07.007Z",
        "created_by": {
            "user_id": "SYSTEM",
            "org_user_id": None,
            "org_id": None,
            "roles": [],
            "scopes": [],
            "allowed_CIDRs": None,
            "cluster_domain": None,
            "proxy_org_user_id": None,
            "tpa_id": None,
            "tpa_name": None,
            "name": None,
        },
        "updated_at": "2021-04-22T07:48:35.072Z",
        "updated_by": {
            "user_id": "usuTaTN12iqG",
            "org_user_id": "ouZH5KbJaBFq",
            "org_id": "orsReFb3Oou8",
            "roles": ["OWNER", "FYLER", "ADMIN"],
            "scopes": [],
            "allowed_CIDRs": [],
            "cluster_domain": '"https://staging.fyle.tech"',
            "proxy_org_user_id": None,
            "tpa_id": None,
            "tpa_name": None,
            "name": "ouZH5KbJaBFq",
        },
        "org_id": "orsReFb3Oou8",
        "column_name": "bus_travel_class",
        "field_name": "Travel Class",
        "seq": 1,
        "type": "TEXT",
        "is_custom": False,
        "is_enabled": True,
        "is_mandatory": False,
        "placeholder": "Enter class of travel",
        "default_value": None,
        "options": [],
        "org_category_ids": [136517],
        "code": None,
        "roles_editable": [
            "FYLER",
            "APPROVER",
            "TRAVEL_ADMIN",
            "VERIFIER",
            "PAYMENT_PROCESSOR",
            "FINANCE",
            "ADMIN",
            "TRAVEL_AGENT",
            "OWNER",
            "AUDITOR",
        ],
    },
    {
        "id": 6183,
        "created_at": "2021-04-22T07:46:07.007Z",
        "created_by": {
            "user_id": "SYSTEM",
            "org_user_id": None,
            "org_id": None,
            "roles": [],
            "scopes": [],
            "allowed_CIDRs": None,
            "cluster_domain": None,
            "proxy_org_user_id": None,
            "tpa_id": None,
            "tpa_name": None,
            "name": None,
        },
        "updated_at": "2021-04-22T07:48:35.072Z",
        "updated_by": {
            "user_id": "usuTaTN12iqG",
            "org_user_id": "ouZH5KbJaBFq",
            "org_id": "orsReFb3Oou8",
            "roles": ["OWNER", "FYLER", "ADMIN"],
            "scopes": [],
            "allowed_CIDRs": [],
            "cluster_domain": '"https://staging.fyle.tech"',
            "proxy_org_user_id": None,
            "tpa_id": None,
            "tpa_name": None,
            "name": "ouZH5KbJaBFq",
        },
        "org_id": "orsReFb3Oou8",
        "column_name": "cost_center_id",
        "field_name": "Cost Center",
        "seq": 1,
        "type": "SELECT",
        "is_custom": False,
        "is_enabled": True,
        "is_mandatory": False,
        "placeholder": "Select Cost Center",
        "default_value": None,
        "options": [],
        "org_category_ids": [
            136506,
            136507,
            136508,
            136509,
            136510,
            136511,
            136512,
            136513,
            136514,
            136515,
            136516,
            136517,
            136518,
            136519,
            136520,
            136521,
            136522,
            136523,
            136524,
            136525,
            136526,
            136527,
            136528,
            136529,
            136530,
            136531,
        ],
        "code": None,
        "roles_editable": [
            "FYLER",
            "APPROVER",
            "TRAVEL_ADMIN",
            "VERIFIER",
            "PAYMENT_PROCESSOR",
            "FINANCE",
            "ADMIN",
            "TRAVEL_AGENT",
            "OWNER",
            "AUDITOR",
        ],
    },
    {
        "id": 6184,
        "created_at": "2021-04-22T07:46:07.007Z",
        "created_by": {
            "user_id": "SYSTEM",
            "org_user_id": None,
            "org_id": None,
            "roles": [],
            "scopes": [],
            "allowed_CIDRs": None,
            "cluster_domain": None,
            "proxy_org_user_id": None,
            "tpa_id": None,
            "tpa_name": None,
            "name": None,
        },
        "updated_at": "2021-04-22T07:48:35.072Z",
        "updated_by": {
            "user_id": "usuTaTN12iqG",
            "org_user_id": "ouZH5KbJaBFq",
            "org_id": "orsReFb3Oou8",
            "roles": ["OWNER", "FYLER", "ADMIN"],
            "scopes": [],
            "allowed_CIDRs": [],
            "cluster_domain": '"https://staging.fyle.tech"',
            "proxy_org_user_id": None,
            "tpa_id": None,
            "tpa_name": None,
            "name": "ouZH5KbJaBFq",
        },
        "org_id": "orsReFb3Oou8",
        "column_name": "distance",
        "field_name": "Distance",
        "seq": 1,
        "type": "NUMBER",
        "is_custom": False,
        "is_enabled": True,
        "is_mandatory": True,
        "placeholder": "Enter Distance",
        "default_value": None,
        "options": [],
        "org_category_ids": [136514],
        "code": None,
        "roles_editable": [
            "FYLER",
            "APPROVER",
            "TRAVEL_ADMIN",
            "VERIFIER",
            "PAYMENT_PROCESSOR",
            "FINANCE",
            "ADMIN",
            "TRAVEL_AGENT",
            "OWNER",
            "AUDITOR",
        ],
    },
    {
        "id": 6185,
        "created_at": "2021-04-22T07:46:07.007Z",
        "created_by": {
            "user_id": "SYSTEM",
            "org_user_id": None,
            "org_id": None,
            "roles": [],
            "scopes": [],
            "allowed_CIDRs": None,
            "cluster_domain": None,
            "proxy_org_user_id": None,
            "tpa_id": None,
            "tpa_name": None,
            "name": None,
        },
        "updated_at": "2021-04-22T07:48:35.072Z",
        "updated_by": {
            "user_id": "usuTaTN12iqG",
            "org_user_id": "ouZH5KbJaBFq",
            "org_id": "orsReFb3Oou8",
            "roles": ["OWNER", "FYLER", "ADMIN"],
            "scopes": [],
            "allowed_CIDRs": [],
            "cluster_domain": '"https://staging.fyle.tech"',
            "proxy_org_user_id": None,
            "tpa_id": None,
            "tpa_name": None,
            "name": "ouZH5KbJaBFq",
        },
        "org_id": "orsReFb3Oou8",
        "column_name": "distance",
        "field_name": "Distance",
        "seq": 2,
        "type": "NUMBER",
        "is_custom": False,
        "is_enabled": True,
        "is_mandatory": False,
        "placeholder": "Enter Distance",
        "default_value": None,
        "options": [],
        "org_category_ids": [136519],
        "code": None,
        "roles_editable": [
            "FYLER",
            "APPROVER",
            "TRAVEL_ADMIN",
            "VERIFIER",
            "PAYMENT_PROCESSOR",
            "FINANCE",
            "ADMIN",
            "TRAVEL_AGENT",
            "OWNER",
            "AUDITOR",
        ],
    },
    {
        "id": 6186,
        "created_at": "2021-04-22T07:46:07.007Z",
        "created_by": {
            "user_id": "SYSTEM",
            "org_user_id": None,
            "org_id": None,
            "roles": [],
            "scopes": [],
            "allowed_CIDRs": None,
            "cluster_domain": None,
            "proxy_org_user_id": None,
            "tpa_id": None,
            "tpa_name": None,
            "name": None,
        },
        "updated_at": "2021-04-22T07:48:35.072Z",
        "updated_by": {
            "user_id": "usuTaTN12iqG",
            "org_user_id": "ouZH5KbJaBFq",
            "org_id": "orsReFb3Oou8",
            "roles": ["OWNER", "FYLER", "ADMIN"],
            "scopes": [],
            "allowed_CIDRs": [],
            "cluster_domain": '"https://staging.fyle.tech"',
            "proxy_org_user_id": None,
            "tpa_id": None,
            "tpa_name": None,
            "name": "ouZH5KbJaBFq",
        },
        "org_id": "orsReFb3Oou8",
        "column_name": "distance_unit",
        "field_name": "Unit",
        "seq": 1,
        "type": "SELECT",
        "is_custom": False,
        "is_enabled": True,
        "is_mandatory": True,
        "placeholder": "Unit",
        "default_value": "MILES",
        "options": ["KM", "MILES"],
        "org_category_ids": [136514],
        "code": None,
        "roles_editable": [
            "FYLER",
            "APPROVER",
            "TRAVEL_ADMIN",
            "VERIFIER",
            "PAYMENT_PROCESSOR",
            "FINANCE",
            "ADMIN",
            "TRAVEL_AGENT",
            "OWNER",
            "AUDITOR",
        ],
    },
    {
        "id": 6187,
        "created_at": "2021-04-22T07:46:07.007Z",
        "created_by": {
            "user_id": "SYSTEM",
            "org_user_id": None,
            "org_id": None,
            "roles": [],
            "scopes": [],
            "allowed_CIDRs": None,
            "cluster_domain": None,
            "proxy_org_user_id": None,
            "tpa_id": None,
            "tpa_name": None,
            "name": None,
        },
        "updated_at": "2021-04-22T07:48:35.072Z",
        "updated_by": {
            "user_id": "usuTaTN12iqG",
            "org_user_id": "ouZH5KbJaBFq",
            "org_id": "orsReFb3Oou8",
            "roles": ["OWNER", "FYLER", "ADMIN"],
            "scopes": [],
            "allowed_CIDRs": [],
            "cluster_domain": '"https://staging.fyle.tech"',
            "proxy_org_user_id": None,
            "tpa_id": None,
            "tpa_name": None,
            "name": "ouZH5KbJaBFq",
        },
        "org_id": "orsReFb3Oou8",
        "column_name": "distance_unit",
        "field_name": "Unit",
        "seq": 2,
        "type": "SELECT",
        "is_custom": False,
        "is_enabled": True,
        "is_mandatory": False,
        "placeholder": "Unit",
        "default_value": "MILES",
        "options": ["KM", "MILES"],
        "org_category_ids": [136519],
        "code": None,
        "roles_editable": [
            "FYLER",
            "APPROVER",
            "TRAVEL_ADMIN",
            "VERIFIER",
            "PAYMENT_PROCESSOR",
            "FINANCE",
            "ADMIN",
            "TRAVEL_AGENT",
            "OWNER",
            "AUDITOR",
        ],
    },
    {
        "id": 6188,
        "created_at": "2021-04-22T07:46:07.007Z",
        "created_by": {
            "user_id": "SYSTEM",
            "org_user_id": None,
            "org_id": None,
            "roles": [],
            "scopes": [],
            "allowed_CIDRs": None,
            "cluster_domain": None,
            "proxy_org_user_id": None,
            "tpa_id": None,
            "tpa_name": None,
            "name": None,
        },
        "updated_at": "2021-04-22T07:48:35.072Z",
        "updated_by": {
            "user_id": "usuTaTN12iqG",
            "org_user_id": "ouZH5KbJaBFq",
            "org_id": "orsReFb3Oou8",
            "roles": ["OWNER", "FYLER", "ADMIN"],
            "scopes": [],
            "allowed_CIDRs": [],
            "cluster_domain": '"https://staging.fyle.tech"',
            "proxy_org_user_id": None,
            "tpa_id": None,
            "tpa_name": None,
            "name": "ouZH5KbJaBFq",
        },
        "org_id": "orsReFb3Oou8",
        "column_name": "flight_journey_travel_class",
        "field_name": "Onward Travel Class",
        "seq": 1,
        "type": "SELECT",
        "is_custom": False,
        "is_enabled": True,
        "is_mandatory": False,
        "placeholder": "Select travel class",
        "default_value": None,
        "options": ["BUSINESS", "ECONOMY", "FIRST_CLASS"],
        "org_category_ids": [136525],
        "code": None,
        "roles_editable": [
            "FYLER",
            "APPROVER",
            "TRAVEL_ADMIN",
            "VERIFIER",
            "PAYMENT_PROCESSOR",
            "FINANCE",
            "ADMIN",
            "TRAVEL_AGENT",
            "OWNER",
            "AUDITOR",
        ],
    },
    {
        "id": 6189,
        "created_at": "2021-04-22T07:46:07.007Z",
        "created_by": {
            "user_id": "SYSTEM",
            "org_user_id": None,
            "org_id": None,
            "roles": [],
            "scopes": [],
            "allowed_CIDRs": None,
            "cluster_domain": None,
            "proxy_org_user_id": None,
            "tpa_id": None,
            "tpa_name": None,
            "name": None,
        },
        "updated_at": "2021-04-22T07:48:35.072Z",
        "updated_by": {
            "user_id": "usuTaTN12iqG",
            "org_user_id": "ouZH5KbJaBFq",
            "org_id": "orsReFb3Oou8",
            "roles": ["OWNER", "FYLER", "ADMIN"],
            "scopes": [],
            "allowed_CIDRs": [],
            "cluster_domain": '"https://staging.fyle.tech"',
            "proxy_org_user_id": None,
            "tpa_id": None,
            "tpa_name": None,
            "name": "ouZH5KbJaBFq",
        },
        "org_id": "orsReFb3Oou8",
        "column_name": "flight_return_travel_class",
        "field_name": "Return Travel Class",
        "seq": 1,
        "type": "SELECT",
        "is_custom": False,
        "is_enabled": True,
        "is_mandatory": False,
        "placeholder": "Select travel class",
        "default_value": None,
        "options": ["BUSINESS", "ECONOMY", "FIRST_CLASS"],
        "org_category_ids": [136525],
        "code": None,
        "roles_editable": [
            "FYLER",
            "APPROVER",
            "TRAVEL_ADMIN",
            "VERIFIER",
            "PAYMENT_PROCESSOR",
            "FINANCE",
            "ADMIN",
            "TRAVEL_AGENT",
            "OWNER",
            "AUDITOR",
        ],
    },
    {
        "id": 6190,
        "created_at": "2021-04-22T07:46:07.007Z",
        "created_by": {
            "user_id": "SYSTEM",
            "org_user_id": None,
            "org_id": None,
            "roles": [],
            "scopes": [],
            "allowed_CIDRs": None,
            "cluster_domain": None,
            "proxy_org_user_id": None,
            "tpa_id": None,
            "tpa_name": None,
            "name": None,
        },
        "updated_at": "2021-04-22T07:48:35.072Z",
        "updated_by": {
            "user_id": "usuTaTN12iqG",
            "org_user_id": "ouZH5KbJaBFq",
            "org_id": "orsReFb3Oou8",
            "roles": ["OWNER", "FYLER", "ADMIN"],
            "scopes": [],
            "allowed_CIDRs": [],
            "cluster_domain": '"https://staging.fyle.tech"',
            "proxy_org_user_id": None,
            "tpa_id": None,
            "tpa_name": None,
            "name": "ouZH5KbJaBFq",
        },
        "org_id": "orsReFb3Oou8",
        "column_name": "from_dt",
        "field_name": "From",
        "seq": 1,
        "type": "DATE",
        "is_custom": False,
        "is_enabled": True,
        "is_mandatory": False,
        "placeholder": "Select Date",
        "default_value": None,
        "options": [],
        "org_category_ids": [136516],
        "code": None,
        "roles_editable": [
            "FYLER",
            "APPROVER",
            "TRAVEL_ADMIN",
            "VERIFIER",
            "PAYMENT_PROCESSOR",
            "FINANCE",
            "ADMIN",
            "TRAVEL_AGENT",
            "OWNER",
            "AUDITOR",
        ],
    },
    {
        "id": 6191,
        "created_at": "2021-04-22T07:46:07.007Z",
        "created_by": {
            "user_id": "SYSTEM",
            "org_user_id": None,
            "org_id": None,
            "roles": [],
            "scopes": [],
            "allowed_CIDRs": None,
            "cluster_domain": None,
            "proxy_org_user_id": None,
            "tpa_id": None,
            "tpa_name": None,
            "name": None,
        },
        "updated_at": "2021-04-22T07:48:35.072Z",
        "updated_by": {
            "user_id": "usuTaTN12iqG",
            "org_user_id": "ouZH5KbJaBFq",
            "org_id": "orsReFb3Oou8",
            "roles": ["OWNER", "FYLER", "ADMIN"],
            "scopes": [],
            "allowed_CIDRs": [],
            "cluster_domain": '"https://staging.fyle.tech"',
            "proxy_org_user_id": None,
            "tpa_id": None,
            "tpa_name": None,
            "name": "ouZH5KbJaBFq",
        },
        "org_id": "orsReFb3Oou8",
        "column_name": "from_dt",
        "field_name": "Onward Date",
        "seq": 2,
        "type": "DATE",
        "is_custom": False,
        "is_enabled": True,
        "is_mandatory": False,
        "placeholder": "Select Date",
        "default_value": None,
        "options": [],
        "org_category_ids": [136507, 136517, 136525],
        "code": None,
        "roles_editable": [
            "FYLER",
            "APPROVER",
            "TRAVEL_ADMIN",
            "VERIFIER",
            "PAYMENT_PROCESSOR",
            "FINANCE",
            "ADMIN",
            "TRAVEL_AGENT",
            "OWNER",
            "AUDITOR",
        ],
    },
    {
        "id": 6192,
        "created_at": "2021-04-22T07:46:07.007Z",
        "created_by": {
            "user_id": "SYSTEM",
            "org_user_id": None,
            "org_id": None,
            "roles": [],
            "scopes": [],
            "allowed_CIDRs": None,
            "cluster_domain": None,
            "proxy_org_user_id": None,
            "tpa_id": None,
            "tpa_name": None,
            "name": None,
        },
        "updated_at": "2021-04-22T07:48:35.072Z",
        "updated_by": {
            "user_id": "usuTaTN12iqG",
            "org_user_id": "ouZH5KbJaBFq",
            "org_id": "orsReFb3Oou8",
            "roles": ["OWNER", "FYLER", "ADMIN"],
            "scopes": [],
            "allowed_CIDRs": [],
            "cluster_domain": '"https://staging.fyle.tech"',
            "proxy_org_user_id": None,
            "tpa_id": None,
            "tpa_name": None,
            "name": "ouZH5KbJaBFq",
        },
        "org_id": "orsReFb3Oou8",
        "column_name": "from_dt",
        "field_name": "Check-in Date",
        "seq": 3,
        "type": "DATE",
        "is_custom": False,
        "is_enabled": True,
        "is_mandatory": False,
        "placeholder": "Select Date",
        "default_value": None,
        "options": [],
        "org_category_ids": [136521],
        "code": None,
        "roles_editable": [
            "FYLER",
            "APPROVER",
            "TRAVEL_ADMIN",
            "VERIFIER",
            "PAYMENT_PROCESSOR",
            "FINANCE",
            "ADMIN",
            "TRAVEL_AGENT",
            "OWNER",
            "AUDITOR",
        ],
    },
    {
        "id": 6193,
        "created_at": "2021-04-22T07:46:07.007Z",
        "created_by": {
            "user_id": "SYSTEM",
            "org_user_id": None,
            "org_id": None,
            "roles": [],
            "scopes": [],
            "allowed_CIDRs": None,
            "cluster_domain": None,
            "proxy_org_user_id": None,
            "tpa_id": None,
            "tpa_name": None,
            "name": None,
        },
        "updated_at": "2021-04-22T07:48:35.072Z",
        "updated_by": {
            "user_id": "usuTaTN12iqG",
            "org_user_id": "ouZH5KbJaBFq",
            "org_id": "orsReFb3Oou8",
            "roles": ["OWNER", "FYLER", "ADMIN"],
            "scopes": [],
            "allowed_CIDRs": [],
            "cluster_domain": '"https://staging.fyle.tech"',
            "proxy_org_user_id": None,
            "tpa_id": None,
            "tpa_name": None,
            "name": "ouZH5KbJaBFq",
        },
        "org_id": "orsReFb3Oou8",
        "column_name": "location1",
        "field_name": "From",
        "seq": 1,
        "type": "LOCATION",
        "is_custom": False,
        "is_enabled": True,
        "is_mandatory": False,
        "placeholder": "Select a City",
        "default_value": None,
        "options": [],
        "org_category_ids": [136507, 136517, 136525],
        "code": None,
        "roles_editable": [
            "FYLER",
            "APPROVER",
            "TRAVEL_ADMIN",
            "VERIFIER",
            "PAYMENT_PROCESSOR",
            "FINANCE",
            "ADMIN",
            "TRAVEL_AGENT",
            "OWNER",
            "AUDITOR",
        ],
    },
    {
        "id": 6194,
        "created_at": "2021-04-22T07:46:07.007Z",
        "created_by": {
            "user_id": "SYSTEM",
            "org_user_id": None,
            "org_id": None,
            "roles": [],
            "scopes": [],
            "allowed_CIDRs": None,
            "cluster_domain": None,
            "proxy_org_user_id": None,
            "tpa_id": None,
            "tpa_name": None,
            "name": None,
        },
        "updated_at": "2021-04-22T07:48:35.072Z",
        "updated_by": {
            "user_id": "usuTaTN12iqG",
            "org_user_id": "ouZH5KbJaBFq",
            "org_id": "orsReFb3Oou8",
            "roles": ["OWNER", "FYLER", "ADMIN"],
            "scopes": [],
            "allowed_CIDRs": [],
            "cluster_domain": '"https://staging.fyle.tech"',
            "proxy_org_user_id": None,
            "tpa_id": None,
            "tpa_name": None,
            "name": "ouZH5KbJaBFq",
        },
        "org_id": "orsReFb3Oou8",
        "column_name": "location1",
        "field_name": "City",
        "seq": 2,
        "type": "LOCATION",
        "is_custom": False,
        "is_enabled": True,
        "is_mandatory": False,
        "placeholder": "Select a City",
        "default_value": None,
        "options": [],
        "org_category_ids": [136521],
        "code": None,
        "roles_editable": [
            "FYLER",
            "APPROVER",
            "TRAVEL_ADMIN",
            "VERIFIER",
            "PAYMENT_PROCESSOR",
            "FINANCE",
            "ADMIN",
            "TRAVEL_AGENT",
            "OWNER",
            "AUDITOR",
        ],
    },
    {
        "id": 6195,
        "created_at": "2021-04-22T07:46:07.007Z",
        "created_by": {
            "user_id": "SYSTEM",
            "org_user_id": None,
            "org_id": None,
            "roles": [],
            "scopes": [],
            "allowed_CIDRs": None,
            "cluster_domain": None,
            "proxy_org_user_id": None,
            "tpa_id": None,
            "tpa_name": None,
            "name": None,
        },
        "updated_at": "2021-04-22T07:48:35.072Z",
        "updated_by": {
            "user_id": "usuTaTN12iqG",
            "org_user_id": "ouZH5KbJaBFq",
            "org_id": "orsReFb3Oou8",
            "roles": ["OWNER", "FYLER", "ADMIN"],
            "scopes": [],
            "allowed_CIDRs": [],
            "cluster_domain": '"https://staging.fyle.tech"',
            "proxy_org_user_id": None,
            "tpa_id": None,
            "tpa_name": None,
            "name": "ouZH5KbJaBFq",
        },
        "org_id": "orsReFb3Oou8",
        "column_name": "location1",
        "field_name": "From",
        "seq": 3,
        "type": "LOCATION",
        "is_custom": False,
        "is_enabled": True,
        "is_mandatory": False,
        "placeholder": "Choose Location - Search for Place or Area",
        "default_value": None,
        "options": [],
        "org_category_ids": [136514],
        "code": None,
        "roles_editable": [
            "FYLER",
            "APPROVER",
            "TRAVEL_ADMIN",
            "VERIFIER",
            "PAYMENT_PROCESSOR",
            "FINANCE",
            "ADMIN",
            "TRAVEL_AGENT",
            "OWNER",
            "AUDITOR",
        ],
    },
    {
        "id": 6196,
        "created_at": "2021-04-22T07:46:07.007Z",
        "created_by": {
            "user_id": "SYSTEM",
            "org_user_id": None,
            "org_id": None,
            "roles": [],
            "scopes": [],
            "allowed_CIDRs": None,
            "cluster_domain": None,
            "proxy_org_user_id": None,
            "tpa_id": None,
            "tpa_name": None,
            "name": None,
        },
        "updated_at": "2021-04-22T07:48:35.072Z",
        "updated_by": {
            "user_id": "usuTaTN12iqG",
            "org_user_id": "ouZH5KbJaBFq",
            "org_id": "orsReFb3Oou8",
            "roles": ["OWNER", "FYLER", "ADMIN"],
            "scopes": [],
            "allowed_CIDRs": [],
            "cluster_domain": '"https://staging.fyle.tech"',
            "proxy_org_user_id": None,
            "tpa_id": None,
            "tpa_name": None,
            "name": "ouZH5KbJaBFq",
        },
        "org_id": "orsReFb3Oou8",
        "column_name": "location2",
        "field_name": "To",
        "seq": 1,
        "type": "LOCATION",
        "is_custom": False,
        "is_enabled": True,
        "is_mandatory": False,
        "placeholder": "Select a City",
        "default_value": None,
        "options": [],
        "org_category_ids": [136507, 136517, 136525],
        "code": None,
        "roles_editable": [
            "FYLER",
            "APPROVER",
            "TRAVEL_ADMIN",
            "VERIFIER",
            "PAYMENT_PROCESSOR",
            "FINANCE",
            "ADMIN",
            "TRAVEL_AGENT",
            "OWNER",
            "AUDITOR",
        ],
    },
    {
        "id": 6197,
        "created_at": "2021-04-22T07:46:07.007Z",
        "created_by": {
            "user_id": "SYSTEM",
            "org_user_id": None,
            "org_id": None,
            "roles": [],
            "scopes": [],
            "allowed_CIDRs": None,
            "cluster_domain": None,
            "proxy_org_user_id": None,
            "tpa_id": None,
            "tpa_name": None,
            "name": None,
        },
        "updated_at": "2021-04-22T07:48:35.072Z",
        "updated_by": {
            "user_id": "usuTaTN12iqG",
            "org_user_id": "ouZH5KbJaBFq",
            "org_id": "orsReFb3Oou8",
            "roles": ["OWNER", "FYLER", "ADMIN"],
            "scopes": [],
            "allowed_CIDRs": [],
            "cluster_domain": '"https://staging.fyle.tech"',
            "proxy_org_user_id": None,
            "tpa_id": None,
            "tpa_name": None,
            "name": "ouZH5KbJaBFq",
        },
        "org_id": "orsReFb3Oou8",
        "column_name": "location2",
        "field_name": "To",
        "seq": 2,
        "type": "LOCATION",
        "is_custom": False,
        "is_enabled": True,
        "is_mandatory": False,
        "placeholder": "Choose Location - Search for Place or Area",
        "default_value": None,
        "options": [],
        "org_category_ids": [136514],
        "code": None,
        "roles_editable": [
            "FYLER",
            "APPROVER",
            "TRAVEL_ADMIN",
            "VERIFIER",
            "PAYMENT_PROCESSOR",
            "FINANCE",
            "ADMIN",
            "TRAVEL_AGENT",
            "OWNER",
            "AUDITOR",
        ],
    },
    {
        "id": 6198,
        "created_at": "2021-04-22T07:46:07.007Z",
        "created_by": {
            "user_id": "SYSTEM",
            "org_user_id": None,
            "org_id": None,
            "roles": [],
            "scopes": [],
            "allowed_CIDRs": None,
            "cluster_domain": None,
            "proxy_org_user_id": None,
            "tpa_id": None,
            "tpa_name": None,
            "name": None,
        },
        "updated_at": "2021-04-22T07:48:35.072Z",
        "updated_by": {
            "user_id": "usuTaTN12iqG",
            "org_user_id": "ouZH5KbJaBFq",
            "org_id": "orsReFb3Oou8",
            "roles": ["OWNER", "FYLER", "ADMIN"],
            "scopes": [],
            "allowed_CIDRs": [],
            "cluster_domain": '"https://staging.fyle.tech"',
            "proxy_org_user_id": None,
            "tpa_id": None,
            "tpa_name": None,
            "name": "ouZH5KbJaBFq",
        },
        "org_id": "orsReFb3Oou8",
        "column_name": "num_days",
        "field_name": "No. of Days",
        "seq": 1,
        "type": "NUMBER",
        "is_custom": False,
        "is_enabled": True,
        "is_mandatory": False,
        "placeholder": "No. of Days",
        "default_value": None,
        "options": [],
        "org_category_ids": [136516],
        "code": None,
        "roles_editable": [
            "FYLER",
            "APPROVER",
            "TRAVEL_ADMIN",
            "VERIFIER",
            "PAYMENT_PROCESSOR",
            "FINANCE",
            "ADMIN",
            "TRAVEL_AGENT",
            "OWNER",
            "AUDITOR",
        ],
    },
    {
        "id": 6199,
        "created_at": "2021-04-22T07:46:07.007Z",
        "created_by": {
            "user_id": "SYSTEM",
            "org_user_id": None,
            "org_id": None,
            "roles": [],
            "scopes": [],
            "allowed_CIDRs": None,
            "cluster_domain": None,
            "proxy_org_user_id": None,
            "tpa_id": None,
            "tpa_name": None,
            "name": None,
        },
        "updated_at": "2021-04-22T07:48:35.072Z",
        "updated_by": {
            "user_id": "usuTaTN12iqG",
            "org_user_id": "ouZH5KbJaBFq",
            "org_id": "orsReFb3Oou8",
            "roles": ["OWNER", "FYLER", "ADMIN"],
            "scopes": [],
            "allowed_CIDRs": [],
            "cluster_domain": '"https://staging.fyle.tech"',
            "proxy_org_user_id": None,
            "tpa_id": None,
            "tpa_name": None,
            "name": "ouZH5KbJaBFq",
        },
        "org_id": "orsReFb3Oou8",
        "column_name": "purpose",
        "field_name": "Purpose",
        "seq": 1,
        "type": "TEXT",
        "is_custom": False,
        "is_enabled": True,
        "is_mandatory": False,
        "placeholder": "E.g. Client Meeting",
        "default_value": None,
        "options": [],
        "org_category_ids": [
            136506,
            136507,
            136508,
            136509,
            136510,
            136511,
            136512,
            136513,
            136514,
            136515,
            136516,
            136517,
            136518,
            136519,
            136520,
            136521,
            136522,
            136523,
            136524,
            136525,
            136526,
            136527,
            136528,
            136529,
            136530,
            136531,
        ],
        "code": None,
        "roles_editable": [
            "FYLER",
            "APPROVER",
            "TRAVEL_ADMIN",
            "VERIFIER",
            "PAYMENT_PROCESSOR",
            "FINANCE",
            "ADMIN",
            "TRAVEL_AGENT",
            "OWNER",
            "AUDITOR",
        ],
    },
    {
        "id": 6200,
        "created_at": "2021-04-22T07:46:07.007Z",
        "created_by": {
            "user_id": "SYSTEM",
            "org_user_id": None,
            "org_id": None,
            "roles": [],
            "scopes": [],
            "allowed_CIDRs": None,
            "cluster_domain": None,
            "proxy_org_user_id": None,
            "tpa_id": None,
            "tpa_name": None,
            "name": None,
        },
        "updated_at": "2021-04-22T07:48:35.072Z",
        "updated_by": {
            "user_id": "usuTaTN12iqG",
            "org_user_id": "ouZH5KbJaBFq",
            "org_id": "orsReFb3Oou8",
            "roles": ["OWNER", "FYLER", "ADMIN"],
            "scopes": [],
            "allowed_CIDRs": [],
            "cluster_domain": '"https://staging.fyle.tech"',
            "proxy_org_user_id": None,
            "tpa_id": None,
            "tpa_name": None,
            "name": "ouZH5KbJaBFq",
        },
        "org_id": "orsReFb3Oou8",
        "column_name": "to_dt",
        "field_name": "To",
        "seq": 1,
        "type": "DATE",
        "is_custom": False,
        "is_enabled": True,
        "is_mandatory": False,
        "placeholder": "Select Date",
        "default_value": None,
        "options": [],
        "org_category_ids": [136516],
        "code": None,
        "roles_editable": [
            "FYLER",
            "APPROVER",
            "TRAVEL_ADMIN",
            "VERIFIER",
            "PAYMENT_PROCESSOR",
            "FINANCE",
            "ADMIN",
            "TRAVEL_AGENT",
            "OWNER",
            "AUDITOR",
        ],
    },
    {
        "id": 6201,
        "created_at": "2021-04-22T07:46:07.007Z",
        "created_by": {
            "user_id": "SYSTEM",
            "org_user_id": None,
            "org_id": None,
            "roles": [],
            "scopes": [],
            "allowed_CIDRs": None,
            "cluster_domain": None,
            "proxy_org_user_id": None,
            "tpa_id": None,
            "tpa_name": None,
            "name": None,
        },
        "updated_at": "2021-04-22T07:48:35.072Z",
        "updated_by": {
            "user_id": "usuTaTN12iqG",
            "org_user_id": "ouZH5KbJaBFq",
            "org_id": "orsReFb3Oou8",
            "roles": ["OWNER", "FYLER", "ADMIN"],
            "scopes": [],
            "allowed_CIDRs": [],
            "cluster_domain": '"https://staging.fyle.tech"',
            "proxy_org_user_id": None,
            "tpa_id": None,
            "tpa_name": None,
            "name": "ouZH5KbJaBFq",
        },
        "org_id": "orsReFb3Oou8",
        "column_name": "to_dt",
        "field_name": "Return Date",
        "seq": 2,
        "type": "DATE",
        "is_custom": False,
        "is_enabled": True,
        "is_mandatory": False,
        "placeholder": "Select Date",
        "default_value": None,
        "options": [],
        "org_category_ids": [136507, 136517, 136525],
        "code": None,
        "roles_editable": [
            "FYLER",
            "APPROVER",
            "TRAVEL_ADMIN",
            "VERIFIER",
            "PAYMENT_PROCESSOR",
            "FINANCE",
            "ADMIN",
            "TRAVEL_AGENT",
            "OWNER",
            "AUDITOR",
        ],
    },
    {
        "id": 6202,
        "created_at": "2021-04-22T07:46:07.007Z",
        "created_by": {
            "user_id": "SYSTEM",
            "org_user_id": None,
            "org_id": None,
            "roles": [],
            "scopes": [],
            "allowed_CIDRs": None,
            "cluster_domain": None,
            "proxy_org_user_id": None,
            "tpa_id": None,
            "tpa_name": None,
            "name": None,
        },
        "updated_at": "2021-04-22T07:48:35.072Z",
        "updated_by": {
            "user_id": "usuTaTN12iqG",
            "org_user_id": "ouZH5KbJaBFq",
            "org_id": "orsReFb3Oou8",
            "roles": ["OWNER", "FYLER", "ADMIN"],
            "scopes": [],
            "allowed_CIDRs": [],
            "cluster_domain": '"https://staging.fyle.tech"',
            "proxy_org_user_id": None,
            "tpa_id": None,
            "tpa_name": None,
            "name": "ouZH5KbJaBFq",
        },
        "org_id": "orsReFb3Oou8",
        "column_name": "to_dt",
        "field_name": "Check-out Date",
        "seq": 3,
        "type": "DATE",
        "is_custom": False,
        "is_enabled": True,
        "is_mandatory": False,
        "placeholder": "Select Date",
        "default_value": None,
        "options": [],
        "org_category_ids": [136521],
        "code": None,
        "roles_editable": [
            "FYLER",
            "APPROVER",
            "TRAVEL_ADMIN",
            "VERIFIER",
            "PAYMENT_PROCESSOR",
            "FINANCE",
            "ADMIN",
            "TRAVEL_AGENT",
            "OWNER",
            "AUDITOR",
        ],
    },
    {
        "id": 6199,
        "created_at": "2021-04-22T07:46:07.007Z",
        "created_by": {
            "user_id": "SYSTEM",
            "org_user_id": None,
            "org_id": None,
            "roles": [],
            "scopes": [],
            "allowed_CIDRs": None,
            "cluster_domain": None,
            "proxy_org_user_id": None,
            "tpa_id": None,
            "tpa_name": None,
            "name": None,
        },
        "updated_at": "2021-04-22T07:48:35.072Z",
        "updated_by": {
            "user_id": "usuTaTN12iqG",
            "org_user_id": "ouZH5KbJaBFq",
            "org_id": "orsReFb3Oou8",
            "roles": ["OWNER", "FYLER", "ADMIN"],
            "scopes": [],
            "allowed_CIDRs": [],
            "cluster_domain": '"https://staging.fyle.tech"',
            "proxy_org_user_id": None,
            "tpa_id": None,
            "tpa_name": None,
            "name": "ouZH5KbJaBFq",
        },
        "org_id": "orsReFb3Oou8",
        "column_name": "train_travel_class",
        "field_name": "Travel class",
        "seq": 1,
        "type": "TEXT",
        "is_custom": False,
        "is_enabled": True,
        "is_mandatory": False,
        "placeholder": "Enter class of travel",
        "default_value": None,
        "options": [],
        "org_category_ids": [136507],
        "code": None,
        "roles_editable": [
            "FYLER",
            "APPROVER",
            "TRAVEL_ADMIN",
            "VERIFIER",
            "PAYMENT_PROCESSOR",
            "FINANCE",
            "ADMIN",
            "TRAVEL_AGENT",
            "OWNER",
            "AUDITOR",
        ],
    },
    {
        "id": 6204,
        "created_at": "2021-04-22T07:46:07.007Z",
        "created_by": {
            "user_id": "SYSTEM",
            "org_user_id": None,
            "org_id": None,
            "roles": [],
            "scopes": [],
            "allowed_CIDRs": None,
            "cluster_domain": None,
            "proxy_org_user_id": None,
            "tpa_id": None,
            "tpa_name": None,
            "name": None,
        },
        "updated_at": "2021-04-22T07:48:35.072Z",
        "updated_by": {
            "user_id": "usuTaTN12iqG",
            "org_user_id": "ouZH5KbJaBFq",
            "org_id": "orsReFb3Oou8",
            "roles": ["OWNER", "FYLER", "ADMIN"],
            "scopes": [],
            "allowed_CIDRs": [],
            "cluster_domain": '"https://staging.fyle.tech"',
            "proxy_org_user_id": None,
            "tpa_id": None,
            "tpa_name": None,
            "name": "ouZH5KbJaBFq",
        },
        "org_id": "orsReFb3Oou8",
        "column_name": "txn_dt",
        "field_name": "Date of Spend",
        "seq": 1,
        "type": "DATE",
        "is_custom": False,
        "is_enabled": True,
        "is_mandatory": True,
        "placeholder": "Select Date",
        "default_value": None,
        "options": [],
        "org_category_ids": [
            136506,
            136507,
            136508,
            136509,
            136510,
            136511,
            136512,
            136513,
            136515,
            136516,
            136517,
            136518,
            136519,
            136520,
            136521,
            136522,
            136523,
            136524,
            136525,
            136526,
            136527,
            136528,
            136529,
            136530,
            136531,
        ],
        "code": None,
        "roles_editable": [
            "FYLER",
            "APPROVER",
            "TRAVEL_ADMIN",
            "VERIFIER",
            "PAYMENT_PROCESSOR",
            "FINANCE",
            "ADMIN",
            "TRAVEL_AGENT",
            "OWNER",
            "AUDITOR",
        ],
    },
    {
        "id": 6205,
        "created_at": "2021-04-22T07:46:07.007Z",
        "created_by": {
            "user_id": "SYSTEM",
            "org_user_id": None,
            "org_id": None,
            "roles": [],
            "scopes": [],
            "allowed_CIDRs": None,
            "cluster_domain": None,
            "proxy_org_user_id": None,
            "tpa_id": None,
            "tpa_name": None,
            "name": None,
        },
        "updated_at": "2021-04-22T07:48:35.072Z",
        "updated_by": {
            "user_id": "usuTaTN12iqG",
            "org_user_id": "ouZH5KbJaBFq",
            "org_id": "orsReFb3Oou8",
            "roles": ["OWNER", "FYLER", "ADMIN"],
            "scopes": [],
            "allowed_CIDRs": [],
            "cluster_domain": '"https://staging.fyle.tech"',
            "proxy_org_user_id": None,
            "tpa_id": None,
            "tpa_name": None,
            "name": "ouZH5KbJaBFq",
        },
        "org_id": "orsReFb3Oou8",
        "column_name": "txn_dt",
        "field_name": "Date of Travel",
        "seq": 2,
        "type": "DATE",
        "is_custom": False,
        "is_enabled": True,
        "is_mandatory": True,
        "placeholder": "Select Date",
        "default_value": None,
        "options": [],
        "org_category_ids": [136514],
        "code": None,
        "roles_editable": [
            "FYLER",
            "APPROVER",
            "TRAVEL_ADMIN",
            "VERIFIER",
            "PAYMENT_PROCESSOR",
            "FINANCE",
            "ADMIN",
            "TRAVEL_AGENT",
            "OWNER",
            "AUDITOR",
        ],
    },
    {
        "id": 6206,
        "created_at": "2021-04-22T07:46:07.007Z",
        "created_by": {
            "user_id": "SYSTEM",
            "org_user_id": None,
            "org_id": None,
            "roles": [],
            "scopes": [],
            "allowed_CIDRs": None,
            "cluster_domain": None,
            "proxy_org_user_id": None,
            "tpa_id": None,
            "tpa_name": None,
            "name": None,
        },
        "updated_at": "2021-04-22T07:48:35.072Z",
        "updated_by": {
            "user_id": "usuTaTN12iqG",
            "org_user_id": "ouZH5KbJaBFq",
            "org_id": "orsReFb3Oou8",
            "roles": ["OWNER", "FYLER", "ADMIN"],
            "scopes": [],
            "allowed_CIDRs": [],
            "cluster_domain": '"https://staging.fyle.tech"',
            "proxy_org_user_id": None,
            "tpa_id": None,
            "tpa_name": None,
            "name": "ouZH5KbJaBFq",
        },
        "org_id": "orsReFb3Oou8",
        "column_name": "vendor_id",
        "field_name": "Merchant",
        "seq": 1,
        "type": "SELECT",
        "is_custom": False,
        "is_enabled": True,
        "is_mandatory": False,
        "placeholder": "E.g. Uber",
        "default_value": None,
        "options": [],
        "org_category_ids": [
            136507,
            136508,
            136509,
            136510,
            136511,
            136512,
            136513,
            136515,
            136517,
            136518,
            136519,
            136520,
            136521,
            136522,
            136523,
            136524,
            136525,
            136526,
            136527,
            136528,
            136529,
            136530,
            136531,
        ],
        "code": None,
        "roles_editable": [
            "FYLER",
            "APPROVER",
            "TRAVEL_ADMIN",
            "VERIFIER",
            "PAYMENT_PROCESSOR",
            "FINANCE",
            "ADMIN",
            "TRAVEL_AGENT",
            "OWNER",
            "AUDITOR",
        ],
    },
    {
        "id": 185323,
        "created_at": "2021-07-28T08:48:55.152Z",
        "created_by": {
            "user_id": "SYSTEM",
            "org_user_id": None,
            "org_id": None,
            "roles": [],
            "scopes": [],
            "allowed_CIDRs": None,
            "cluster_domain": None,
            "proxy_org_user_id": None,
            "tpa_id": None,
            "tpa_name": None,
            "name": None,
        },
        "updated_at": "2021-07-28T08:48:55.152Z",
        "updated_by": {
            "user_id": "SYSTEM",
            "org_user_id": None,
            "org_id": None,
            "roles": [],
            "scopes": [],
            "allowed_CIDRs": None,
            "cluster_domain": None,
            "proxy_org_user_id": None,
            "tpa_id": None,
            "tpa_name": None,
            "name": None,
        },
        "org_id": "orsReFb3Oou8",
        "column_name": "project_id",
        "field_name": "Project",
        "seq": 1,
        "type": "SELECT",
        "is_custom": False,
        "is_enabled": True,
        "is_mandatory": False,
        "placeholder": "Select Project",
        "default_value": None,
        "options": [],
        "org_category_ids": [],
        "code": None,
        "roles_editable": [
            "FYLER",
            "APPROVER",
            "TRAVEL_ADMIN",
            "VERIFIER",
            "PAYMENT_PROCESSOR",
            "FINANCE",
            "ADMIN",
            "TRAVEL_AGENT",
            "OWNER",
            "AUDITOR",
        ],
    },
    {
        "id": 189621,
        "created_at": "2021-07-29T11:05:38.811Z",
        "created_by": {
            "user_id": "SYSTEM",
            "org_user_id": None,
            "org_id": None,
            "roles": [],
            "scopes": [],
            "allowed_CIDRs": None,
            "cluster_domain": None,
            "proxy_org_user_id": None,
            "tpa_id": None,
            "tpa_name": None,
            "name": None,
        },
        "updated_at": "2021-07-29T11:05:38.811Z",
        "updated_by": {
            "user_id": "SYSTEM",
            "org_user_id": None,
            "org_id": None,
            "roles": [],
            "scopes": [],
            "allowed_CIDRs": None,
            "cluster_domain": None,
            "proxy_org_user_id": None,
            "tpa_id": None,
            "tpa_name": None,
            "name": None,
        },
        "org_id": "orsReFb3Oou8",
        "column_name": "billable",
        "field_name": "Billable",
        "seq": 1,
        "type": "BOOLEAN",
        "is_custom": False,
        "is_enabled": True,
        "is_mandatory": False,
        "placeholder": "Billable",
        "default_value": "False",
        "options": [],
        "org_category_ids": [],
        "code": None,
        "roles_editable": [
            "FYLER",
            "APPROVER",
            "TRAVEL_ADMIN",
            "VERIFIER",
            "PAYMENT_PROCESSOR",
            "FINANCE",
            "ADMIN",
            "TRAVEL_AGENT",
            "OWNER",
            "AUDITOR",
        ],
    },
    {
        "id": 194141,
        "created_at": "2021-08-17T04:48:57.792Z",
        "created_by": {
            "user_id": "SYSTEM",
            "org_user_id": None,
            "org_id": None,
            "roles": [],
            "scopes": [],
            "allowed_CIDRs": None,
            "cluster_domain": None,
            "proxy_org_user_id": None,
            "tpa_id": None,
            "tpa_name": None,
            "name": None,
        },
        "updated_at": "2021-08-17T04:48:57.792Z",
        "updated_by": {
            "user_id": "SYSTEM",
            "org_user_id": None,
            "org_id": None,
            "roles": [],
            "scopes": [],
            "allowed_CIDRs": None,
            "cluster_domain": None,
            "proxy_org_user_id": None,
            "tpa_id": None,
            "tpa_name": None,
            "name": None,
        },
        "org_id": "orsReFb3Oou8",
        "column_name": "tax_group",
        "field_name": "Tax Group",
        "seq": 1,
        "type": "SELECT",
        "is_custom": False,
        "is_enabled": True,
        "is_mandatory": False,
        "placeholder": "Tax Group",
        "default_value": None,
        "options": [],
        "org_category_ids": [],
        "code": None,
        "roles_editable": [
            "FYLER",
            "APPROVER",
            "TRAVEL_ADMIN",
            "VERIFIER",
            "PAYMENT_PROCESSOR",
            "FINANCE",
            "ADMIN",
            "TRAVEL_AGENT",
            "OWNER",
            "AUDITOR",
        ],
    },
    {
        "id": 195217,
        "created_at": "2021-08-18T07:35:59.906Z",
        "created_by": {
            "user_id": "usuTaTN12iqG",
            "org_user_id": "ouZH5KbJaBFq",
            "org_id": "orsReFb3Oou8",
            "roles": ["OWNER", "FYLER", "ADMIN", "APPROVER"],
            "scopes": [],
            "allowed_CIDRs": [],
            "cluster_domain": '"https://staging.fyle.tech"',
            "proxy_org_user_id": None,
            "tpa_id": None,
            "tpa_name": None,
            "name": "ouZH5KbJaBFq",
        },
        "updated_at": "2021-08-18T07:35:59.906Z",
        "updated_by": {
            "user_id": "usuTaTN12iqG",
            "org_user_id": "ouZH5KbJaBFq",
            "org_id": "orsReFb3Oou8",
            "roles": ["OWNER", "FYLER", "ADMIN", "APPROVER"],
            "scopes": [],
            "allowed_CIDRs": [],
            "cluster_domain": '"https://staging.fyle.tech"',
            "proxy_org_user_id": None,
            "tpa_id": None,
            "tpa_name": None,
            "name": "ouZH5KbJaBFq",
        },
        "org_id": "orsReFb3Oou8",
        "column_name": "text_column1",
        "field_name": "TEST 1",
        "seq": 1,
        "type": "TEXT",
        "is_custom": True,
        "is_enabled": True,
        "is_mandatory": True,
        "placeholder": "testiing",
        "default_value": None,
        "options": [],
        # "org_category_ids": [136250, 136518], - For two custom fields
        "org_category_ids": [136250],
        "code": None,
        "roles_editable": [
            "FYLER",
            "APPROVER",
            "TRAVEL_ADMIN",
            "VERIFIER",
            "PAYMENT_PROCESSOR",
            "FINANCE",
            "ADMIN",
            "TRAVEL_AGENT",
            "OWNER",
            "AUDITOR",
        ],
    },
    {
        "id": 195510,
        "created_at": "2021-08-23T13:18:38.309Z",
        "created_by": {
            "user_id": "usuTaTN12iqG",
            "org_user_id": "ouZH5KbJaBFq",
            "org_id": "orsReFb3Oou8",
            "roles": ["OWNER", "FYLER", "ADMIN", "APPROVER"],
            "scopes": [],
            "allowed_CIDRs": [],
            "cluster_domain": '"https://staging.fyle.tech"',
            "proxy_org_user_id": None,
            "tpa_id": None,
            "tpa_name": None,
            "name": "ouZH5KbJaBFq",
        },
        "updated_at": "2021-08-23T13:18:38.309Z",
        "updated_by": {
            "user_id": "usuTaTN12iqG",
            "org_user_id": "ouZH5KbJaBFq",
            "org_id": "orsReFb3Oou8",
            "roles": ["OWNER", "FYLER", "ADMIN", "APPROVER"],
            "scopes": [],
            "allowed_CIDRs": [],
            "cluster_domain": '"https://staging.fyle.tech"',
            "proxy_org_user_id": None,
            "tpa_id": None,
            "tpa_name": None,
            "name": "ouZH5KbJaBFq",
        },
        "org_id": "orsReFb3Oou8",
        "column_name": "text_column2",
        "field_name": "Test select field",
        "seq": 1,
        "type": "SELECT",
        "is_custom": True,
        "is_enabled": True,
        "is_mandatory": False,
        "placeholder": "testing select fields",
        "default_value": None,
        "options": ["test choice 1", "test choice 2"],
        "org_category_ids": [136518],
        "code": None,
        "roles_editable": [
            "FYLER",
            "APPROVER",
            "TRAVEL_ADMIN",
            "VERIFIER",
            "PAYMENT_PROCESSOR",
            "FINANCE",
            "ADMIN",
            "TRAVEL_AGENT",
            "OWNER",
            "AUDITOR",
        ],
    },
]

categories = [
    {
        "id": 835229,
        "created_at": "2019-02-13T08:24:43.405Z",
        "updated_at": "2019-02-13T08:24:44.405Z",
        "org_id": "orKPte3WEwuJ",
        "name": "Activity",
        "code": None,
        "fyle_category": "Activity",
        "sub_category": "Activity",
        "enabled": True,
        "creator_id": None,
        "last_updated_by": None,
    },
    {
        "id": 835240,
        "created_at": "2019-02-13T08:24:43.463Z",
        "updated_at": "2019-02-13T08:24:44.463Z",
        "org_id": "orKPte3WEwuJ",
        "name": "Bus",
        "code": None,
        "fyle_category": "Bus",
        "sub_category": "Bus",
        "enabled": True,
        "creator_id": None,
        "last_updated_by": None,
    },
    {
        "id": 835243,
        "created_at": "2019-02-13T08:24:43.476Z",
        "updated_at": "2019-02-13T08:24:44.476Z",
        "org_id": "orKPte3WEwuJ",
        "name": "Courier",
        "code": None,
        "fyle_category": "Courier",
        "sub_category": "Courier",
        "enabled": True,
        "creator_id": None,
        "last_updated_by": None,
    },
    {
        "id": 835235,
        "created_at": "2019-02-13T08:24:43.441Z",
        "updated_at": "2019-02-13T08:24:44.441Z",
        "org_id": "orKPte3WEwuJ",
        "name": "Entertainment",
        "code": None,
        "fyle_category": "Entertainment",
        "sub_category": "Entertainment",
        "enabled": True,
        "creator_id": None,
        "last_updated_by": None,
    },
    {
        "id": 835248,
        "created_at": "2019-02-13T08:24:43.498Z",
        "updated_at": "2019-02-13T08:24:44.498Z",
        "org_id": "orKPte3WEwuJ",
        "name": "Flight",
        "code": None,
        "fyle_category": "Flight",
        "sub_category": "Flight",
        "enabled": True,
        "creator_id": None,
        "last_updated_by": None,
    },
    {
        "id": 835238,
        "created_at": "2019-02-13T08:24:43.455Z",
        "updated_at": "2019-02-13T08:24:44.455Z",
        "org_id": "orKPte3WEwuJ",
        "name": "Food",
        "code": None,
        "fyle_category": "Food",
        "sub_category": "Food",
        "enabled": True,
        "creator_id": None,
        "last_updated_by": None,
    },
    {
        "id": 835231,
        "created_at": "2019-02-13T08:24:43.413Z",
        "updated_at": "2019-02-13T08:24:44.413Z",
        "org_id": "orKPte3WEwuJ",
        "name": "Fuel",
        "code": None,
        "fyle_category": "Fuel",
        "sub_category": "Fuel",
        "enabled": True,
        "creator_id": None,
        "last_updated_by": None,
    },
    {
        "id": 835244,
        "created_at": "2019-02-13T08:24:43.481Z",
        "updated_at": "2019-02-13T08:24:44.481Z",
        "org_id": "orKPte3WEwuJ",
        "name": "Hotel",
        "code": None,
        "fyle_category": "Hotel",
        "sub_category": "Hotel",
        "enabled": True,
        "creator_id": None,
        "last_updated_by": None,
    },
    {
        "id": 835241,
        "created_at": "2019-02-13T08:24:43.468Z",
        "updated_at": "2019-02-13T08:24:44.468Z",
        "org_id": "orKPte3WEwuJ",
        "name": "Internet",
        "code": None,
        "fyle_category": "Internet",
        "sub_category": "Internet",
        "enabled": True,
        "creator_id": None,
        "last_updated_by": None,
    },
    {
        "id": 835237,
        "created_at": "2019-02-13T08:24:43.451Z",
        "updated_at": "2019-02-13T08:24:44.451Z",
        "org_id": "orKPte3WEwuJ",
        "name": "Mileage",
        "code": None,
        "fyle_category": "Mileage",
        "sub_category": "Mileage",
        "enabled": True,
        "creator_id": None,
        "last_updated_by": None,
    },
    {
        "id": 835247,
        "created_at": "2019-02-13T08:24:43.494Z",
        "updated_at": "2019-02-13T08:24:44.494Z",
        "org_id": "orKPte3WEwuJ",
        "name": "Office Party",
        "code": None,
        "fyle_category": "Office Party",
        "sub_category": "Office Party",
        "enabled": True,
        "creator_id": None,
        "last_updated_by": None,
    },
    {
        "id": 835233,
        "created_at": "2019-02-13T08:24:43.421Z",
        "updated_at": "2019-02-13T08:24:44.421Z",
        "org_id": "orKPte3WEwuJ",
        "name": "Office Supplies",
        "code": None,
        "fyle_category": "Office Supplies",
        "sub_category": "Office Supplies",
        "enabled": True,
        "creator_id": None,
        "last_updated_by": None,
    },
    {
        "id": 835236,
        "created_at": "2019-02-13T08:24:43.447Z",
        "updated_at": "2019-02-13T08:24:44.447Z",
        "org_id": "orKPte3WEwuJ",
        "name": "Others",
        "code": None,
        "fyle_category": "Others",
        "sub_category": "Others",
        "enabled": True,
        "creator_id": None,
        "last_updated_by": None,
    },
    {
        "id": 835250,
        "created_at": "2019-02-13T08:24:43.507Z",
        "updated_at": "2019-02-13T08:24:44.507Z",
        "org_id": "orKPte3WEwuJ",
        "name": "Parking",
        "code": None,
        "fyle_category": "Parking",
        "sub_category": "Parking",
        "enabled": True,
        "creator_id": None,
        "last_updated_by": None,
    },
    {
        "id": 835239,
        "created_at": "2019-02-13T08:24:43.459Z",
        "updated_at": "2019-02-13T08:24:44.459Z",
        "org_id": "orKPte3WEwuJ",
        "name": "Per Diem",
        "code": None,
        "fyle_category": "Per Diem",
        "sub_category": "Per Diem",
        "enabled": True,
        "creator_id": None,
        "last_updated_by": None,
    },
    {
        "id": 835246,
        "created_at": "2019-02-13T08:24:43.489Z",
        "updated_at": "2019-02-13T08:24:44.489Z",
        "org_id": "orKPte3WEwuJ",
        "name": "Phone",
        "code": None,
        "fyle_category": "Phone",
        "sub_category": "Phone",
        "enabled": True,
        "creator_id": None,
        "last_updated_by": None,
    },
    {
        "id": 835245,
        "created_at": "2019-02-13T08:24:43.485Z",
        "updated_at": "2019-02-13T08:24:44.485Z",
        "org_id": "orKPte3WEwuJ",
        "name": "Professional Services",
        "code": None,
        "fyle_category": "Professional Services",
        "sub_category": "Professional Services",
        "enabled": True,
        "creator_id": None,
        "last_updated_by": None,
    },
    {
        "id": 835232,
        "created_at": "2019-02-13T08:24:43.417Z",
        "updated_at": "2019-02-13T08:24:44.417Z",
        "org_id": "orKPte3WEwuJ",
        "name": "Snacks",
        "code": None,
        "fyle_category": "Snacks",
        "sub_category": "Snacks",
        "enabled": True,
        "creator_id": None,
        "last_updated_by": None,
    },
    {
        "id": 835249,
        "created_at": "2019-02-13T08:24:43.502Z",
        "updated_at": "2019-02-13T08:24:44.502Z",
        "org_id": "orKPte3WEwuJ",
        "name": "Software",
        "code": None,
        "fyle_category": "Software",
        "sub_category": "Software",
        "enabled": True,
        "creator_id": None,
        "last_updated_by": None,
    },
    {
        "id": 835252,
        "created_at": "2019-02-13T08:24:43.515Z",
        "updated_at": "2019-02-13T08:24:44.515Z",
        "org_id": "orKPte3WEwuJ",
        "name": "Tax",
        "code": None,
        "fyle_category": "Tax",
        "sub_category": "Tax",
        "enabled": True,
        "creator_id": None,
        "last_updated_by": None,
    },
    {
        "id": 835242,
        "created_at": "2019-02-13T08:24:43.472Z",
        "updated_at": "2019-02-13T08:24:44.472Z",
        "org_id": "orKPte3WEwuJ",
        "name": "Taxi",
        "code": None,
        "fyle_category": "Taxi",
        "sub_category": "Taxi",
        "enabled": True,
        "creator_id": None,
        "last_updated_by": None,
    },
    {
        "id": 835251,
        "created_at": "2019-02-13T08:24:43.511Z",
        "updated_at": "2019-02-13T08:24:44.511Z",
        "org_id": "orKPte3WEwuJ",
        "name": "Toll Charge",
        "code": None,
        "fyle_category": "Toll Charge",
        "sub_category": "Toll Charge",
        "enabled": True,
        "creator_id": None,
        "last_updated_by": None,
    },
    {
        "id": 835230,
        "created_at": "2019-02-13T08:24:43.409Z",
        "updated_at": "2019-02-13T08:24:44.409Z",
        "org_id": "orKPte3WEwuJ",
        "name": "Train",
        "code": None,
        "fyle_category": "Train",
        "sub_category": "Train",
        "enabled": True,
        "creator_id": None,
        "last_updated_by": None,
    },
    {
        "id": 835253,
        "created_at": "2019-02-13T08:24:43.522Z",
        "updated_at": "2019-02-13T08:24:44.522Z",
        "org_id": "orKPte3WEwuJ",
        "name": "Training",
        "code": None,
        "fyle_category": "Training",
        "sub_category": "Training",
        "enabled": True,
        "creator_id": None,
        "last_updated_by": None,
    },
    {
        "id": 835254,
        "created_at": "2019-02-13T08:24:43.526Z",
        "updated_at": "2019-02-13T08:24:44.526Z",
        "org_id": "orKPte3WEwuJ",
        "name": "Unspecified",
        "code": None,
        "fyle_category": "Unspecified",
        "sub_category": "Unspecified",
        "enabled": True,
        "creator_id": None,
        "last_updated_by": None,
    },
    {
        "id": 835234,
        "created_at": "2019-02-13T08:24:43.426Z",
        "updated_at": "2019-02-13T08:24:44.426Z",
        "org_id": "orKPte3WEwuJ",
        "name": "Utility",
        "code": None,
        "fyle_category": "Utility",
        "sub_category": "Utility",
        "enabled": True,
        "creator_id": None,
        "last_updated_by": None,
    },
]
