apiVersion: v1
kind: Service
metadata:
  name: slack-app
  namespace: slack
  labels:
    app: slack-app
spec:
  type: ClusterIP
  ports:
    - port: 8000
  selector:
    app: slack-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: slack-app
  namespace: slack
  labels:
    app: slack-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slack-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: slack-app
    spec:
      containers:
        - name: slack-app
          image: docker.io/sivafyle/fyle_slack-app:${version}
          resources:
            limits:
              memory: 200Mi
            requests:
              memory: 200Mi
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
            initialDelaySeconds: 10
            timeoutSeconds: 1
          env:
            - name: FYLE_ACCOUNTS_URL
              value: https://staging-accounts.fyle.tech
            - name: FYLE_APP_URL
              value: https://staging1.fyle.tech
            - name: ALLOWED_HOSTS
              value: '*'
            - name: DEBUG
              value: 'False'
            - name: FYLE_BRANCHIO_BASE_URI
              value: https://fyle.app.link
            - name: SLACK_SERVICE_BASE_URL
              value: https://slack.fyle.tech
            - name: FYLE_STOPLIGHT_URL
              value: https://stoplight.io/mocks/fyle/fyle-platform-docs
          envFrom:
            - secretRef:
                name: slack-app-secrets
      terminationGracePeriodSeconds: 60
      imagePullSecrets:
        - name: myregistrykey2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: slack-app-qcluster
  namespace: slack
  labels:
    app: slack-app-qcluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slack-app-qcluster
  template:
    metadata:
      labels:
        app: slack-app-qcluster
    spec:
      containers:
        - name: slack-app
          image: docker.io/sivafyle/fyle_slack-app:${version}
          resources:
            limits:
              memory: 400Mi
            requests:
              memory: 400Mi
          command: [ 'bash', 'run_qcluster.sh' ]
          env:
            - name: FYLE_ACCOUNTS_URL
              value: https://staging-accounts.fyle.tech
            - name: FYLE_APP_URL
              value: https://staging1.fyle.tech
            - name: ALLOWED_HOSTS
              value: '*'
            - name: DEBUG
              value: 'False'
            - name: FYLE_BRANCHIO_BASE_URI
              value: https://fyle.app.link
            - name: SLACK_SERVICE_BASE_URL
              value: https://slack.fyle.tech
          envFrom:
            - secretRef:
                name: slack-app-secrets
      terminationGracePeriodSeconds: 60
      imagePullSecrets:
        - name: myregistrykey2
